# ecosystem-workflows.md ArchR block on real 10x PBMC 5k chr1 slice. Documented args used except relaxed QC (slice is 3% of genome).
suppressPackageStartupMessages({library(ArchR)})
SCA <- Sys.getenv("SCA"); D <- Sys.getenv("ATACDATA")
W <- file.path(SCA,"work/archr"); unlink(W, recursive=TRUE); dir.create(W,recursive=TRUE); setwd(W)
addArchRThreads(threads=6); addArchRGenome('hg38')
fr <- file.path(D,"scatac/outs/fragments.tsv.gz")
# as documented (minTSS=4, minFrags=1000)
ar0 <- tryCatch(createArrowFiles(inputFiles=fr, sampleNames='doc', minTSS=4, minFrags=1000, addTileMat=TRUE, addGeneScoreMat=TRUE, force=TRUE),
                error=function(e){cat("DOC-AS-WRITTEN createArrowFiles(minTSS=4,minFrags=1000) ->", conditionMessage(e), "\n"); NULL})
cat("documented-threshold arrow:", if(is.null(ar0)) "none" else ar0, "\n")
ArrowFiles <- createArrowFiles(inputFiles=fr, sampleNames='rep1', minTSS=1, minFrags=500, addTileMat=TRUE, addGeneScoreMat=TRUE, force=TRUE)
doubletScores <- addDoubletScores(input=ArrowFiles, k=10, knnMethod='UMAP')
proj <- ArchRProject(ArrowFiles=ArrowFiles, outputDirectory='ArchR_out')
n0 <- nrow(getCellColData(proj)); proj <- filterDoublets(proj); cat("cells before/after filterDoublets", n0, nrow(getCellColData(proj)), "\n")
cd <- as.data.frame(getCellColData(proj)); cat("nFrags range", range(cd$nFrags), " TSSEnrichment range", round(range(cd$TSSEnrichment),2), "\n")
proj <- addIterativeLSI(proj, useMatrix='TileMatrix', name='IterativeLSI')
proj <- addClusters(proj, reducedDims='IterativeLSI', method='Seurat', resolution=0.5)
proj <- addUMAP(proj, reducedDims='IterativeLSI')
cat("clusters", table(proj$Clusters), "\n")
proj <- addGroupCoverages(proj, groupBy='Clusters')
mac <- Sys.getenv("MACS3"); cat("macs3 at", mac, "\n")
proj <- addReproduciblePeakSet(proj, groupBy='Clusters', pathToMacs2=mac)
ps <- getPeakSet(proj); cat("reproducible peaks", length(ps), "chr", unique(as.character(seqnames(ps))), " width median", median(width(ps)), "\n")
proj <- addPeakMatrix(proj)
pm <- getMatrixFromProject(proj, "PeakMatrix"); cat("PeakMatrix", dim(pm), "\n")
gs <- getMatrixFromProject(proj, "GeneScoreMatrix"); cat("GeneScoreMatrix", dim(gs), "\n")
p <- plotEmbedding(proj, colorBy="cellColData", name="Clusters", embedding="UMAP")
png(file.path(Sys.getenv("AUDOUT"),"archr_umap.png"), 700, 600, res=100); print(p); dev.off()
saveRDS(list(cd=cd, nclus=table(proj$Clusters)), file.path(W,"summary.rds"))
