suppressPackageStartupMessages({library(Signac);library(Seurat)})
o <- readRDS(file.path(Sys.getenv("SCA"),"work/patched/scatac_signac.rds"))
cat("cells",ncol(o)," assays",paste(Assays(o),collapse=","),"\n")
cat("clusters",table(o$seurat_clusters),"\n")
cat("nCount_ATAC range",range(o$nCount_ATAC),"\n")
cat("TSS range",range(o$TSS.enrichment),"nucsig",range(o$nucleosome_signal),"\n")
cat("frip range",range(o$pct_reads_in_peaks),"\n")
cat("depth cor of LSI dims 1..5:", round(sapply(1:5,function(i) cor(Embeddings(o,"lsi")[,i],log10(o$nCount_ATAC))),2),"\n")
cat("ACT genes",nrow(o[["ACT"]]),"dim",dim(o[["ACT"]]),"\n")
cat("umap dims",dim(Embeddings(o,"umap")),"\n")
cat("lsi assay chr", head(unique(as.character(seqnames(granges(o[["ATAC"]])))),3),"\n")
