"""
Input 1 (Canonical) execution.
Runs the exact `gi_score` function as documented in the Skill's own SKILL.md
("Genetic Interaction (GI) Scoring" section), unmodified, against the
synthetic paired_lfc.tsv / single_lfc.tsv generated by gen_synthetic_data.py.
"""
import pandas as pd
import numpy as np
from scipy.stats import zscore


def gi_score(paired_lfc_df, single_lfc_df):
    '''Score genetic interactions from paired vs single LFCs.

    paired_lfc_df: rows = paired-KO; columns = ['gene_A', 'gene_B', 'paired_lfc']
    single_lfc_df: rows = single-KO; columns = ['gene', 'single_lfc']
    '''
    single = dict(zip(single_lfc_df['gene'], single_lfc_df['single_lfc']))
    df = paired_lfc_df.copy()
    df['single_A_lfc'] = df['gene_A'].map(single)
    df['single_B_lfc'] = df['gene_B'].map(single)
    df['expected_additive'] = df['single_A_lfc'] + df['single_B_lfc']
    df['gi_score'] = df['paired_lfc'] - df['expected_additive']
    df = df.dropna(subset=['gi_score'])          # a single missing singleton would NaN every z-score
    df['gi_z'] = zscore(df['gi_score'])
    df['gi_class'] = np.where(df['gi_z'] < -2, 'synthetic_lethal',
                                np.where(df['gi_z'] > 2, 'synthetic_rescue', 'no_interaction'))
    return df.sort_values('gi_z')


paired_raw = pd.read_csv('paired_lfc.tsv', sep='\t')
single_raw = pd.read_csv('single_lfc.tsv', sep='\t')

# Aggregate cassette-level to pair-level first (as the skill's own workflow
# step 6 "Aggregate to per-pair LFCs across replicate cassettes" requires) --
# the SKILL.md gi_score() signature expects one row per pair with a
# 'paired_lfc' column, not per-cassette rows.
pair_level = (
    paired_raw.groupby(['gene_A', 'gene_B'])['lfc']
    .mean()
    .reset_index()
    .rename(columns={'lfc': 'paired_lfc'})
)
single_level = single_raw.rename(columns={'lfc': 'single_lfc'})

result = gi_score(pair_level, single_level)
result.to_csv('gi_scores_input1.tsv', sep='\t', index=False)

print(result.to_string(index=False))
print()
sl = result[result['gi_class'] == 'synthetic_lethal']
sr = result[result['gi_class'] == 'synthetic_rescue']
print(f"Synthetic-lethal pairs called (z < -2): {len(sl)} -> {list(zip(sl['gene_A'], sl['gene_B']))}")
print(f"Synthetic-rescue pairs called (z > 2): {len(sr)} -> {list(zip(sr['gene_A'], sr['gene_B']))}")
