root <- "/mnt/openscience/audit-envs/bio-comparative-genomics-ancestral-reconstruction"
sink(file.path(root,"evidence","ouwie-probe.log"),split=TRUE)
on.exit(sink(),add=TRUE)
library(ape)
library(OUwie)
print(args(OUwie))
print(args(OUwie.anc))
set.seed(20260928)
tree <- rtree(24)
tree$tip.label <- sprintf("ou_%02d",seq_len(24))
tree <- phytools::force.ultrametric(tree, method="extend")
data <- data.frame(species=tree$tip.label,regime=rep(1,24),trait=fastBM(tree,a=2,sig2=.2))
candidate_fit <- tryCatch({x <- OUwie(tree,data,model="OU1"); paste("accepted",class(x)[1])},error=function(e) paste(class(e)[1],conditionMessage(e)))
fit <- OUwie(tree,data,model="OU1",simmap.tree=FALSE,quiet=TRUE,check.identify=FALSE)
cat("fit_class",class(fit),"AICc",fit$AICc,"\n")
candidate_call <- tryCatch({OUwie.anc(fit,data=data); "accepted"},error=function(e) paste(class(e)[1],conditionMessage(e)))
valid_call <- tryCatch({x <- OUwie.anc(fit,knowledge=TRUE); paste("accepted",class(x)[1])},error=function(e) paste(class(e)[1],conditionMessage(e)))
cat("candidate_fit",candidate_fit,"\n")
cat("candidate_call",candidate_call,"\n")
cat("valid_call",valid_call,"\n")

