#!/usr/bin/env bash
###############################################################################
# Auto-generated by qiime2 v.2024.10.1 at 08:13:51 AM on 19 Sep, 2026
# This document is a representation of the scholarly work of the creator of the
# QIIME 2 Results provided as input to this software, and may be protected by
# intellectual property law. Please respect all copyright restrictions and
# licenses governing the use, modification, and redistribution of this work.

# For User Support, post to the QIIME2 Forum at https://forum.qiime2.org.

# Instructions for use:
# 1. Open this script in a text editor or IDE. Support for BASH
#    syntax highlighting can be helpful.
# 2. Search or scan visually for '<' or '>' characters to find places where
#    user input (e.g. a filepath or column name) is required. These must be
#    replaced with your own values. E.g. <column name> -> 'patient_id'.
#    Failure to remove '<' or '>' may result in `No such File ...` errors
# 3. Search for 'FIXME' comments in the script, and respond as directed.
# 4. Remove all 'FIXME' comments from the script completely. Failure to do so
#    may result in 'Missing Option' errors
# 5. Adjust the arguments to the commands below to suit your data and metadata.
#    If your data is not identical to that in the replayed analysis,
#    changes may be required. (e.g. sample ids or rarefaction depth)
# 6. Optional: replace any filenames in this script that begin with 'XX' with
#    unique file names to ensure they are preserved. QIIME 2 saves all outputs
#    from all actions in this script to disk regardless of whether those
#    outputs were in the original collection of replayed results. The filenames
#    of "un-replayed" artifacts are prefixed with 'XX' so they may be easily
#    located. These names are not guaranteed to be unique, so 'XX_table.qza'
#    may be overwritten by another 'XX_table.qza' later in the script.
# 7. Activate your replay conda environment, and confirm you have installed all
#    plugins used by the script.
# 8. Run this script with `bash <path to this script>`, or copy-paste commands
#    into the terminal for a more interactive analysis.
# 9. Optional: to delete all results not required to produce the figures and
#    data used to generate this script, navigate to the directory in which you
#    ran the script and `rm XX*.qz*`
###############################################################################
## function to create result collections ##
construct_result_collection () {
	mkdir $rc_name
	touch $rc_name.order
	for key in "${keys[@]}"; do
		echo $key >> $rc_name.order
	done
	for i in "${!keys[@]}"; do
		ln -s ../"${names[i]}" $rc_name"${keys[i]}"$ext
	done
}
##

# This tells bash to -e exit immediately if a command fails
# and -x show all commands in stdout so you can track progress
set -e -x

qiime tools import \
  --type 'SampleData[PairedEndSequencesWithQuality]' \
  --input-path <your data here> \
  --output-path sample-data-paired-end-sequences-with-quality-0.qza

qiime dada2 denoise-paired \
  --i-demultiplexed-seqs sample-data-paired-end-sequences-with-quality-0.qza \
  --p-trunc-len-f 0 \
  --p-trunc-len-r 0 \
  --p-trim-left-f 0 \
  --p-trim-left-r 0 \
  --p-max-ee-f 2.0 \
  --p-max-ee-r 2.0 \
  --p-trunc-q 2 \
  --p-min-overlap 12 \
  --p-pooling-method independent \
  --p-chimera-method consensus \
  --p-min-fold-parent-over-abundance 1.0 \
  --p-no-allow-one-off \
  --p-n-threads 1 \
  --p-n-reads-learn 1000000 \
  --p-hashed-feature-ids \
  --p-retain-all-samples \
  --o-table table-0.qza \
  --o-representative-sequences XX_representative_sequences \
  --o-denoising-stats XX_denoising_stats


###############################################################################
# The following QIIME 2 Results were parsed to produce this script:
# 0c48908e-d19a-4ee2-bc90-c1e5870eb5d9
###############################################################################
