# GG-004 label collision matrix: measured label boxes (mm) from the drawn ggrepel grobs, plus rendered PNGs.
# Usage: r.sh|r-gg35.sh r2_labels.R <skilldir> <outdir>
a <- commandArgs(TRUE); skill <- a[1]; out <- a[2]; dir.create(out, FALSE, TRUE)
here <- dirname(sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE)))
suppressMessages({library(ggplot2); library(ggrepel); library(patchwork); library(grid)})
cat("ggplot2", as.character(packageVersion("ggplot2")), "\n")
suppressMessages(source(file.path(skill, "scripts/publication_figures.R"))); source(file.path(here, "lib_overlap.R"))
setwd(out)
raw <- read.csv("F:/OpenScience/audit-envs/data-visualization/public-data/differential-expression/airway_dex_deseq2_results.csv")
# gene symbols for the SKILL's "short gene symbols" advice
sym <- suppressMessages(AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db, keys = raw$gene, column = "SYMBOL", keytype = "ENSEMBL", multiVals = "first"))
raw$symbol <- ifelse(is.na(sym), raw$gene, sym)
set.seed(7); df <- data.frame(g = rep(c("A","B","C"), each = 20), v = c(rnorm(20), rnorm(20, 1), rnorm(20, 2)))
pc <- prcomp(mtcars[, -1], scale. = TRUE); ve <- 100 * pc$sdev^2 / sum(pc$sdev^2)
pdf_ <- data.frame(pc$x[, 1:2], cyl = factor(mtcars$cyl), am = factor(mtcars$am), var_explained = ve[1:2])
bp <- create_boxplot(df, "g", "v", "g"); pp <- create_pca_plot(pdf_, "cyl", "am")

keys <- c("standalone_top10_w183", "standalone_top3_w89", "multi3_default_183x120", "multi4_default_183x150", "multi4_top3_183x150", "multi4_symbols10_183x150")
row <- function(tag, plot, w, h, save = TRUE) {
  if (nzchar(Sys.getenv("KEYONLY")) && !(tag %in% keys)) return(invisible(NULL))   # KEYONLY=1: key rows only (ggplot2 3.5.2 cross-check)
  b <- label_boxes(plot, w, h); o <- overlaps(b); x <- outside(b)
  n_all <- if (is.null(b)) 0 else nrow(b)
  cat(sprintf("%-46s %3.0f x %3.0f mm | labels drawn %2d | overlapping pairs %d | outside panel %d%s\n", tag, w, h, n_all, nrow(o), nrow(x),
              if (nrow(o)) paste0(" [", paste(sprintf("%s~%s(%.1fx%.1f)", o$a, o$b, o$ox_mm, o$oy_mm), collapse = "; "), "]") else ""))
  if (save) ggsave(paste0(gsub("[^A-Za-z0-9]+", "_", tag), ".png"), plot, width = w, height = h, units = "mm", dpi = 200)
  invisible(list(b = b, o = o))
}
cat("\n-- standalone create_volcano, Ensembl IDs, defaults (top_n = 10)\n")
v10 <- create_volcano(raw)
for (w in c(183, 120, 89)) row(sprintf("standalone_top10_w%d", w), v10, w, w * 0.7)
cat("\n-- standalone, top_n = 3 / symbols\n")
v3 <- create_volcano(raw, top_n = 3)
row("standalone_top3_w89", v3, 89, 70)
vs <- create_volcano(raw, label_col = "symbol")
row("standalone_symbols10_w89", vs, 89, 70)
row("standalone_symbols10_w183", vs, 183, 128)
cat("\n-- create_multi_panel as shipped (volcano default top_n = 10)\n")
m3 <- create_multi_panel(v10, bp, pp); m4 <- create_multi_panel(v10, bp, pp, bp)
row("multi3_default_183x120", m3, 183, 120); row("multi3_default_183x150", m3, 183, 150)
row("multi4_default_183x150", m4, 183, 150)
row("multi3_default_120x110", m3, 120, 110)
cat("\n-- create_multi_panel with the Skill's advice (top_n = 3)\n")
m3b <- create_multi_panel(v3, bp, pp); m4b <- create_multi_panel(v3, bp, pp, bp)
row("multi3_top3_183x120", m3b, 183, 120); row("multi3_top3_183x150", m3b, 183, 150)
row("multi4_top3_183x150", m4b, 183, 150); row("multi4_top3_183x120", m4b, 183, 120)
row("multi4_top3_120x110", m4b, 120, 110)
cat("\n-- multi-panel with symbols (top_n = 10)\n")
m4s <- create_multi_panel(vs, bp, pp, bp); row("multi4_symbols10_183x150", m4s, 183, 150)
m3s <- create_multi_panel(vs, bp, pp); row("multi3_symbols10_183x120", m3s, 183, 120)
cat("\n-- same-width control: volcano alone at the width it gets in the 4-panel (about 85 mm)\n")
row("control_top10_w85", v10, 85, 62); row("control_top3_w85", v3, 85, 62)
