# references/geoms-scales-facets.md: every code line built (warnings recorded) and rendered once.
a <- commandArgs(TRUE); out <- a[1]; dir.create(out, FALSE, TRUE); setwd(out)
suppressMessages({library(ggplot2); library(ggrepel); library(scico); library(viridis)})
cat("ggplot2", as.character(packageVersion("ggplot2")), "\n")
W <- character(0); hw <- function(w) { W <<- c(W, conditionMessage(w)); invokeRestart("muffleWarning") }
df <- data.frame(x = rep(c("Control", "Treatment", "Vehicle"), each = 20), y = c(rnorm(20), rnorm(20, 1), rnorm(20, 2)), z = rnorm(60), k = rep(c("a", "b"), 30), g = rep(c("g1","g2","g3"), 20), l = paste0("L", 1:60), t = rep(c("early","late"), each = 30))
set.seed(2); df$y <- abs(df$y) + 1
t1 <- function(label, expr) { W <<- character(0); ok <- tryCatch({ b <- withCallingHandlers(ggplot_build(expr), warning = hw); ggsave(tempfile(fileext = ".png"), expr, width = 60, height = 50, units = "mm", dpi = 72); TRUE }, error = function(e) { cat("ERROR", conditionMessage(e), "\n"); FALSE })
  cat(sprintf("[%s] %s%s\n", if (ok && !length(W)) "PASS" else if (ok) "WARN" else "FAIL", label, if (length(W)) paste0(" :: ", paste(unique(W), collapse = " | ")) else "")) }
P <- ggplot(df, aes(x, y))
t1("geom_point alpha/size", P + geom_point(alpha = 0.7, size = 1))
t1("geom_line linewidth", ggplot(df, aes(z, y)) + geom_line(linewidth = 0.5))
t1("geom_col", P + geom_col())
t1("geom_bar", ggplot(df, aes(x)) + geom_bar())
t1("geom_boxplot outlier.shape NA", P + geom_boxplot(outlier.shape = NA))
t1("geom_violin bw SJ trim FALSE", P + geom_violin(bw = 'SJ', trim = FALSE))
t1("geom_histogram bins", ggplot(df, aes(y)) + geom_histogram(bins = 30))
t1("geom_density alpha", ggplot(df, aes(y)) + geom_density(alpha = 0.5))
t1("geom_tile fill", ggplot(df, aes(x, k, fill = z)) + geom_tile())
t1("geom_text check_overlap", ggplot(df, aes(z, y, label = l)) + geom_text(aes(label = l), check_overlap = TRUE))
t1("geom_text_repel max.overlaps Inf", ggplot(df, aes(z, y, label = l)) + geom_text_repel(aes(label = l), max.overlaps = Inf))
t1("scale_x_continuous limits/breaks/label_number", ggplot(df, aes(z * 1e6, y)) + geom_point() + scale_x_continuous(limits = c(-5e6, 5e6), breaks = seq(-4e6, 4e6, 2e6), labels = scales::label_number(scale = 1e-6, suffix = 'M')))
t1("scale_y_log10", P + geom_point() + scale_y_log10())
t1("scale_y_continuous sqrt", P + geom_point() + scale_y_continuous(transform = 'sqrt'))
t1("scale_x_discrete limits", P + geom_point() + scale_x_discrete(limits = c('Control', 'Treatment', 'Vehicle')))
t1("scale_color_manual named", ggplot(df, aes(z, y, color = x)) + geom_point() + scale_color_manual(values = c(Control = '#0072B2', Treatment = '#D55E00', Vehicle = '#009E73')))
t1("scale_color_viridis_c", ggplot(df, aes(z, y, color = z)) + geom_point() + scale_color_viridis_c(option = 'viridis'))
t1("scale_color_scico batlow", ggplot(df, aes(z, y, color = z)) + geom_point() + scale_color_scico(palette = 'batlow'))
t1("scale_fill_gradient2", ggplot(df, aes(x, k, fill = z)) + geom_tile() + scale_fill_gradient2(low = '#0072B2', mid = 'white', high = '#D55E00', midpoint = 0))
dd <- data.frame(d = seq(as.Date("2018-01-01"), by = "month", length.out = 60), v = 1:60)
t1("scale_x_date", ggplot(dd, aes(d, v)) + geom_line() + scale_x_date(date_breaks = '1 year', date_labels = '%Y'))
t1("facet_wrap free_y", P + geom_point() + facet_wrap(~ g, ncol = 3, scales = 'free_y'))
t1("facet_grid vars", P + geom_point() + facet_grid(rows = vars(k), cols = vars(t), scales = 'free_x'))
t1("facet_grid formula", P + geom_point() + facet_grid(k ~ t))
