"""Input 1 (Canonical) - bio-single-cell-preprocessing
Response code generated by following SKILL.md: Quality Control section (MAD-adaptive,
per-sample groupby block at SKILL.md:81-86), Normalization, HVG, Scaling sections,
and the Canonical Pipeline Order.

Data: SYNTHETIC 8-sample PBMC set
  F:/OpenScience/audits/_partial-20260911/bio-workflows-scrnaseq-pipeline/data/synthetic_pbmc_8samples
"""
import scanpy as sc
import numpy as np
import pandas as pd
from scipy.stats import median_abs_deviation

D = r'F:/OpenScience/audits/_partial-20260911/bio-workflows-scrnaseq-pipeline/data/synthetic_pbmc_8samples'
OUT = r'F:/OpenScience/audits/bio-single-cell-preprocessing/run'

adata = sc.read_h5ad(D + '/all_samples_filtered.h5ad')
print(f'Loaded: {adata.n_obs} cells, {adata.n_vars} genes, {adata.obs["sample"].nunique()} samples')

# --- SKILL.md Quality Control block, verbatim gene-set annotation ---
adata.var['mt'] = adata.var_names.str.startswith('MT-')
adata.var['ribo'] = adata.var_names.str.startswith(('RPS', 'RPL'))
adata.var['hb'] = adata.var_names.str.contains(r'^HB[ABDEGMQZ]\d*(?!\w)')
print('mito genes:', int(adata.var["mt"].sum()), '| ribo:', int(adata.var["ribo"].sum()),
      '| hb:', int(adata.var["hb"].sum()))

sc.pp.calculate_qc_metrics(adata, qc_vars=['mt', 'ribo', 'hb'], percent_top=[20],
                           log1p=True, inplace=True)


def is_outlier(adata, metric, nmads):
    M = adata.obs[metric]
    return (M < np.median(M) - nmads * median_abs_deviation(M)) | (np.median(M) + nmads * median_abs_deviation(M) < M)


# --- global MAD (SKILL.md:72-75) for comparison ---
glob_outlier = (is_outlier(adata, 'log1p_total_counts', 5) | is_outlier(adata, 'log1p_n_genes_by_counts', 5)
                | is_outlier(adata, 'pct_counts_in_top_20_genes', 5))
glob_mt = is_outlier(adata, 'pct_counts_mt', 3) | (adata.obs['pct_counts_mt'] > 8)
print(f'GLOBAL MAD: count/gene/top20 outliers={int(glob_outlier.sum())}, mito outliers={int(glob_mt.sum())}, '
      f'total flagged={int((glob_outlier | glob_mt).sum())}')

# --- SKILL.md:81-86 per-sample block, run VERBATIM to test it ---
flags = ['log1p_total_counts', 'log1p_n_genes_by_counts', 'pct_counts_in_top_20_genes']
try:
    per_sample = adata.obs.groupby('sample', observed=True).apply(
        lambda g: (is_outlier(adata[g.index], flags[0], 5) | is_outlier(adata[g.index], flags[1], 5)
                   | is_outlier(adata[g.index], flags[2], 5))).droplevel(0)
    print('SKILL per-sample block: OK, dtype', per_sample.dtype, 'len', len(per_sample))
    print('  index aligned with adata.obs_names:', bool((per_sample.index == adata.obs_names).all()))
    verbatim_ok = True
except Exception as e:
    print('SKILL per-sample block FAILED:', type(e).__name__, str(e)[:400])
    verbatim_ok = False

# --- adapted per-sample MAD (what a careful agent writes when the verbatim block is unusable) ---
out = pd.Series(False, index=adata.obs_names)
mt_out = pd.Series(False, index=adata.obs_names)
for s, idx in adata.obs.groupby('sample', observed=True).groups.items():
    sub = adata[idx]
    o = (is_outlier(sub, flags[0], 5) | is_outlier(sub, flags[1], 5) | is_outlier(sub, flags[2], 5))
    m = is_outlier(sub, 'pct_counts_mt', 3) | (sub.obs['pct_counts_mt'] > 8)
    out.loc[idx] = o.values
    mt_out.loc[idx] = m.values
    print(f'  {s}: n={sub.n_obs} median_counts={np.median(sub.obs["total_counts"]):.0f} '
          f'median_mito={np.median(sub.obs["pct_counts_mt"]):.2f}% count/gene outliers={int(o.sum())} mito outliers={int(m.sum())}')

adata.obs['outlier'] = out
adata.obs['mt_outlier'] = mt_out
removed = (adata.obs['outlier'] | adata.obs['mt_outlier'])
print(f'PER-SAMPLE MAD: total flagged={int(removed.sum())} ({100*removed.mean():.1f}%)')

# --- score against ground truth (SYNTHETIC truth labels) ---
truth = pd.read_csv(D + '/truth_cells.csv').set_index('cell_id')
truth = truth.loc[adata.obs_names]
lq = truth['true_low_quality'].values
print('\nGROUND TRUTH CHECK (synthetic labels):')
for name, mask in [('global MAD', (glob_outlier | glob_mt).values), ('per-sample MAD', removed.values)]:
    tp = int((mask & lq).sum()); fp = int((mask & ~lq).sum()); fn = int((~mask & lq).sum())
    print(f'  {name}: removed {int(mask.sum())}  TP={tp} FP={fp} FN={fn}  '
          f'recall={tp/max(tp+fn,1):.3f} precision={tp/max(tp+fp,1):.3f}')
    # which true cell types were lost
    lost = truth.loc[mask & ~lq, 'true_cell_type'].value_counts()
    tot = truth['true_cell_type'].value_counts()
    frac = (lost / tot).dropna().sort_values(ascending=False)
    print('    good cells lost by type (frac of that type):',
          {k: f'{v:.3f}' for k, v in frac.head(4).items()})

adata = adata[~removed].copy()
sc.pp.filter_genes(adata, min_cells=3)
print(f'\nAfter QC: {adata.n_obs} cells, {adata.n_vars} genes')

# --- Normalization (SKILL.md:138-142) ---
adata.layers['counts'] = adata.X.copy()
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)

# --- HVG (SKILL.md:164-166) ---
sc.pp.highly_variable_genes(adata, n_top_genes=2000, flavor='seurat_v3', layer='counts',
                            batch_key='sample')
print('HVGs:', int(adata.var.highly_variable.sum()))

# demonstrate the Skill's headline gotcha: seurat_v3 on log-normalised values
import anndata
wrong = anndata.AnnData(X=adata.X.copy(), obs=adata.obs[[]].copy(), var=adata.var[[]].copy())
try:
    sc.pp.highly_variable_genes(wrong, n_top_genes=2000, flavor='seurat_v3')
    ov = len(set(adata.var_names[adata.var.highly_variable]) & set(wrong.var_names[wrong.var.highly_variable]))
    print(f'seurat_v3 on LOG-NORMALISED data: ran without error, {ov}/2000 HVGs shared with the correct run')
except Exception as e:
    print('seurat_v3 on log data raised:', type(e).__name__, str(e)[:200])

# --- PCA on HVG, no scaling (SKILL.md:38 of example / Scaling section) ---
sc.pp.pca(adata, mask_var='highly_variable')
print('PCA:', adata.obsm['X_pca'].shape)
adata.write_h5ad(OUT + '/input1_preprocessed.h5ad')
print('Saved input1_preprocessed.h5ad')
print('VERBATIM_SKILL_BLOCK_OK =', verbatim_ok)
