# Input 4 (Variant B -- allele-aware subclones) -- code as generated by
# Claude following bio-single-cell-cnv-inference SKILL.md's "Numbat" section,
# adapted only in file paths, against a synthetic count matrix +
# EXPLICITLY FABRICATED allele table (see make_numbat_allele_synth.R for the
# caveat: no real BAM/phasing pipeline was run; this tests the documented R
# API's code usability, not phasing/allele-calling accuracy).
# Prompt: "I have BAM files and want the best possible subclone resolution
# with copy-neutral LOH detection - walk me through running Numbat."
suppressMessages(library(numbat))

data_dir  <- "/mnt/openscience/audits/bio-single-cell-cnv-inference/data_realgenes"
snp_dir   <- "/mnt/openscience/audits/bio-single-cell-cnv-inference/run/numbat_allele_data"
out_dir   <- "/mnt/openscience/audits/bio-single-cell-cnv-inference/run/numbat_out_input4"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

counts <- read.table(file.path(data_dir, "counts.matrix"), header = TRUE,
                      row.names = 1, sep = "\t", check.names = FALSE)
annot_all <- read.table(file.path(data_dir, "cell_annotations.txt"), sep = "\t",
                         col.names = c("cell", "group"))
df_allele <- read.table(file.path(snp_dir, "df_allele.tsv"), sep = "\t", header = TRUE)

# restrict count_mat to the same cells present in df_allele (reference + CloneA)
keep_cells <- unique(df_allele$cell)
count_mat <- as.matrix(counts[, keep_cells])
cell_annot <- annot_all[annot_all$cell %in% keep_cells, ]

# build the expression reference from matched normals, per SKILL.md:
# `aggregate_counts(count_mat, cell_annot)` where cell_annot has cell/group
ref_cells_mat <- as.matrix(counts[, cell_annot$cell[cell_annot$group %in% c("Tcell", "Myeloid")]])
ref_annot <- cell_annot[cell_annot$group %in% c("Tcell", "Myeloid"), ]
lambdas_ref <- aggregate_counts(ref_cells_mat, ref_annot)

cat("count_mat dim:", dim(count_mat), "\n")
cat("df_allele rows:", nrow(df_allele), "\n")
cat("lambdas_ref dim:", dim(lambdas_ref), "\n")

out <- run_numbat(
    count_mat,
    lambdas_ref = lambdas_ref,
    df_allele = df_allele,
    genome = "hg38",
    t = 1e-5,
    ncores = 2,
    max_iter = 1,
    plot = FALSE,
    out_dir = out_dir)

nb <- Numbat$new(out_dir = out_dir)
cat("\n=== clone_post head ===\n")
print(head(nb$clone_post))
message("Numbat complete; inspect ", out_dir)
