# Input 2 (Variant A -- reference-free) -- code as generated by Claude
# following bio-single-cell-cnv-inference SKILL.md's copyKAT section,
# adapted only in file paths, against the audit's synthetic dataset.
# Prompt: "I don't have any annotated normal cells in my tumor sample -
# which reference-free CNV-inference method should I use, and how do I run it?"
#
# The skill's method-choice table recommends copyKAT or SCEVAN when no
# reference cells are annotated. This script follows the copyKAT code block
# (SKILL.md, "copyKAT - reference-free aneuploid vs diploid").
library(copykat)

data_dir <- "/mnt/openscience/audits/bio-single-cell-cnv-inference/data_realgenes"
dir.create("/mnt/openscience/audits/bio-single-cell-cnv-inference/run/copykat_out_input2", showWarnings = FALSE)
setwd("/mnt/openscience/audits/bio-single-cell-cnv-inference/run/copykat_out_input2")

counts <- read.table(file.path(data_dir, "counts.matrix"), header = TRUE,
                      row.names = 1, sep = "\t", check.names = FALSE)
exp_rawdata <- as.matrix(counts)
cat("exp_rawdata dim:", dim(exp_rawdata), "\n")

# NOTE (audit harness, not a skill defect): default min.gene.per.cell=200
# filters out every cell of this deliberately small 180-gene synthetic panel
# (real datasets carry thousands of genes). Lowered to fit the panel size;
# SKILL.md's code block does not set this parameter at all.
res <- copykat(
    rawmat = exp_rawdata,
    id.type = "S",
    ngene.chr = 5,
    min.gene.per.cell = 50,
    win.size = 25,
    KS.cut = 0.1,
    sam.name = "tumor1",
    distance = "euclidean",
    norm.cell.names = "",
    genome = "hg20",
    n.cores = 4)

pred <- res$prediction
cna  <- res$CNAmat

cat("\n=== copyKAT prediction table ===\n")
print(table(pred$copykat.pred))
write.csv(pred, "copykat_prediction.csv", row.names = FALSE)
saveRDS(res, "copykat_result.rds")
message("copyKAT complete")
