# Input 1 (Canonical) -- code as generated by Claude following
# bio-single-cell-cnv-inference SKILL.md / examples/infercnv_malignant_calling.R,
# adapted only in file paths, against the audit's synthetic dataset.
# Prompt: "I have a tumor scRNA-seq dataset with annotated T cells and myeloid
# cells. Which cells are malignant, and what CNVs do they carry? Run inferCNV
# using my immune cells as the normal reference."
library(infercnv)

data_dir <- "/mnt/openscience/audits/bio-single-cell-cnv-inference/data"
out_dir  <- "/mnt/openscience/audits/bio-single-cell-cnv-inference/run/infercnv_out_input1_rerun"

infercnv_obj <- CreateInfercnvObject(
    raw_counts_matrix = file.path(data_dir, "counts.matrix"),
    annotations_file  = file.path(data_dir, "cell_annotations.txt"),
    delim = "\t",
    gene_order_file = file.path(data_dir, "gene_ordering.txt"),
    ref_group_names = c("Tcell", "Myeloid"))

infercnv_obj <- infercnv::run(
    infercnv_obj,
    cutoff = 0.1,
    out_dir = out_dir,
    cluster_by_groups = TRUE,
    denoise = TRUE,
    HMM = TRUE,
    HMM_type = "i6",
    num_threads = 4)

obs <- read.table(file.path(out_dir, "infercnv.observations.txt"), header = TRUE, row.names = 1)
cnv_score <- colSums((obs - 1)^2)
malignant <- cnv_score > quantile(cnv_score, 0.5)

cat("\n=== per-cell malignant calls (threshold = median CNV score) ===\n")
print(table(malignant))
cat("\n=== top 10 cnv_score cells ===\n")
print(sort(cnv_score, decreasing = TRUE)[1:10])
saveRDS(list(cnv_score = cnv_score, malignant = malignant), file.path(out_dir, "malignant_calls.rds"))
write.csv(data.frame(cell = names(cnv_score), cnv_score = cnv_score, malignant = malignant),
          file.path(out_dir, "malignant_calls.csv"), row.names = FALSE)
message("inferCNV complete; inspect ", out_dir)
