suppressPackageStartupMessages({library(DiffBind)})
setwd("/mnt/openscience/audits/bio-atac-seq-differential-accessibility/reaudit-run/work")
d <- dba(sampleSheet="samples.csv"); d <- dba.count(d, summits=250, minOverlap=2, bParallel=FALSE)
d <- dba.normalize(d, normalize=DBA_NORM_LIB, library=DBA_LIBSIZE_FULL)
d <- dba.contrast(d, design=TRUE, contrast=c("Condition","treated","control"), minMembers=2); d <- dba.analyze(d, method=DBA_DESEQ2)
a <- dba.report(d, method=DBA_DESEQ2, th=0.05, fold=1); b <- dba.report(d, method=DBA_DESEQ2, th=1, fold=0); c2 <- dba.report(d, method=DBA_DESEQ2, th=0.05, fold=0)
cat("th.05 fold1:", length(a), " th1 fold0:", length(b), " th.05 fold0:", length(c2), "\n")
cat("range |Fold| in th.05 fold0:", range(abs(c2$Fold)), "  n with |Fold|>=1:", sum(abs(c2$Fold)>=1), "\n")
cat("range |Fold| in a:", range(abs(a$Fold)), "\n")
cat("th=1 report FDR range:", range(b$FDR), " n FDR<.05:", sum(b$FDR<.05), "\n")
for (f in c(0.5,1,2,3)) { r <- dba.report(d, method=DBA_DESEQ2, th=0.05, fold=f); cat(sprintf("fold=%.1f: n=%d min|Fold|=%.3f  n(|Fold|>=f in fold0 set)=%d\n", f, length(r), min(abs(r$Fold)), sum(abs(c2$Fold)>=f))) }
drop <- c2[!overlapsAny(c2,a,type="equal")]; cat("dropped by fold=1 but |Fold|>=1:", sum(abs(drop$Fold)>=1), " their |Fold| range:", range(abs(drop$Fold[abs(drop$Fold)>=1])), "\n")
print(head(as.data.frame(mcols(drop)[abs(drop$Fold)>=1,]),3))
print(args(DiffBind:::pv.DBAreport))
