suppressPackageStartupMessages({library(JASPAR2024);library(TFBSTools);library(RSQLite)})
j <- JASPAR2024()
r <- try(getMatrixSet(j, opts=list(collection='CORE', tax_group='vertebrates')), silent=TRUE)
cat("direct getMatrixSet(JASPAR2024 obj):", if (inherits(r,"try-error")) paste("ERROR:", substr(as.character(r),1,160)) else paste("OK", length(r)), "\n")
sq <- dbConnect(SQLite(), db(j)); r2 <- getMatrixSet(sq, opts=list(collection='CORE', tax_group='vertebrates'))
cat("sqlite workaround:", length(r2), "\n")
r3 <- getMatrixSet(sq, opts=list(collection='CORE', tax_group='vertebrates', all_versions=FALSE)); cat("all_versions=FALSE:",length(r3),"\n")
r4 <- getMatrixSet(sq, opts=list(collection='CORE', tax_group='vertebrates', all_versions=TRUE)); cat("all_versions=TRUE:",length(r4),"\n")
cat("db:", db(j), "\n"); cat("TFBSTools", as.character(packageVersion("TFBSTools")), "JASPAR2024", as.character(packageVersion("JASPAR2024")), "\n")
