import json, sys
A = lambda t, r, n: {"text": t, "result": r, "note": n}
spec = {
"meta": {"skill_name": "bio-data-visualization-matplotlib-fundamentals", "description": "Build publication-quality figures with matplotlib using the OO Figure/Axes API, constrained layout, Type-42 font embedding and CVD-safe palettes, with seaborn integration; ships scripts/matplotlib_phd.py.", "evaluated_on": "2026-10-03", "category": "Data Analysis", "execution_mode": "D", "complexity": "Moderate"},
"veto_gates": {"skill_veto": {"gate": "PASS", "stability": "PASS", "contract": "PASS", "determinism": "PASS", "security": "PASS"},
 "research_veto": {"applicable": True, "gate": "PASS",
  "scientific_integrity": {"result": "PASS", "detail": "No fabricated values; the shipped example uses labelled synthetic data. On real airway results (541 Up / 497 Down / 17,200 NS) the Skill's list-palette recipe drew correct points but with data-order-dependent colours (MPL-002), filed as a defect."},
  "practice_boundaries": {"result": "PASS", "detail": "Plotting skill; no clinical or prescriptive output."},
  "methodological_ground": {"result": "PASS", "detail": "No principled fallacy; colour-to-class binding by list order is a presentation hazard (MPL-002), not an inverted statistical conclusion."},
  "code_usability": {"result": "PASS", "detail": "matplotlib_phd.py and every recipe ran unchanged on matplotlib 3.11.2 with exit 0; defects are page size, palette binding and doc claims (MPL-001..MPL-006)."}}},
"static": {
 "functional_suitability": {"score": 9, "note": "Covers rcParams, OO API, layout, fonts, saving and seaborn; the shipped rcParams break the 89 mm promise (MPL-001) and the list-palette recipe mis-binds colours (MPL-002)."},
 "reliability": {"score": 9, "note": "All shipped code runs cleanly on 3.11.2 with no warnings; behaviour hazards are silent (page size, palette order)."},
 "performance_context": {"score": 6, "note": "Compact SKILL.md routing to two references; recipes and guardrails repeat across SKILL.md, usage-guide and failure-modes."},
 "agent_usability": {"score": 12, "note": "Clear defaults and guardrails; an agent following the Standard Setup gets 89.4 mm output while the script gives 92.0 mm (MPL-001)."},
 "human_usability": {"score": 6, "note": "Readable; usage-guide mixes pyplot calls into an OO-API Skill (MPL-006)."},
 "security": {"score": 11, "note": "Local file writes only; no credentials or network."},
 "maintainability": {"score": 9, "note": "Single example script mirrors SKILL.md; no tests or palette-binding checks."},
 "agent_specific": {"score": 15, "note": "Precise trigger and routed references; failure-modes.md contains a nonexistent method and an exaggerated size claim (MPL-003)."}},
"inputs": [
 {"type": "Canonical", "label": "Run scripts/matplotlib_phd.py unchanged: rcParams, 89 mm scatter, 2x3 grid, Crameri heatmap, seaborn scatter, seaborn.objects", "status": "COMPLETED", "note": "Exit 0, five PDFs, all fonts CID TrueType embedded; pages are 92.0 / 182.7 / 91.8 mm wide against documented 89 / 180 / 89 mm (MPL-001); cluster colours are tab10 (MPL-005).", "basic": 30, "specialized": 43,
  "assertions": [A("Script exits 0 and writes five PDFs with no warnings", "PASS", "Exit 0, stderr empty."),
   A("Every PDF embeds TrueType fonts and has no Type 3 rows", "PASS", "pdffonts: ArialMT/Arial-BoldMT CID TrueType, emb yes, in all five."),
   A("89 mm and 180 mm figures are saved at the documented journal widths", "FAIL", "MediaBox 92.0 x 73.0, 91.8 x 93.0, 182.7 x 113.0 mm (savefig.bbox 'tight' with default pad)."),
   A("Scatter and heatmap rasterise the data layer and keep text vector", "PASS", "image XObjects present (2 / 12); text embedded as fonts.")]},
 {"type": "Variant A", "label": "SKILL.md seaborn volcano recipe on real airway DESeq2 results (18,238 genes)", "status": "COMPLETED", "note": "Points correct but the list palette binds by order of appearance: Up drawn blue and Down orange; the shipped example colours 'ns' orange (MPL-002).", "basic": 28, "specialized": 38,
  "assertions": [A("NS points are drawn in the documented grey #999999", "PASS", "Legend NS = #999999 on the airway data, by luck of data order."),
   A("Up is orange and Down is blue as the usage-guide's Up/Down/NS colours imply", "FAIL", "Legend Up = #0072b2, Down = #d55e00 on real data; on the shipped random data ns = orange."),
   A("A dict palette with hue_order fixes class colours", "PASS", "Control: NS grey, Down blue, Up orange."),
   A("rasterized=True shrinks the 18,238-point PDF", "PASS", "38,984 B versus 272,530 B vector.")]},
 {"type": "Edge", "label": "SKILL.md Standard Setup rcParams and Saving block: PDF, PNG, TIFF, SVG, EPS at 89 mm", "status": "COMPLETED", "note": "PNG/TIFF 1056 x 831 px (89.4 x 70.4 mm) with the Skill's pad 0.05; TIFF LZW works; SVG text is converted to paths so the 'editable vector' claim fails (MPL-004).", "basic": 30, "specialized": 40,
  "assertions": [A("Standard Setup figure saves within 1 mm of 89 mm", "PASS", "89.4 mm wide with pad_inches 0.05."),
   A("TIFF save uses LZW compression", "PASS", "PIL reports tiff_lzw, 1056 x 831."),
   A("SVG keeps text as editable <text>", "FAIL", "0 <text> elements, 55 glyph <use> (svg.fonttype 'path')."),
   A("Default Type 3 versus pdf.fonttype=42 claim", "PASS", "pdffonts: stock rcParams give Type 3 DejaVuSans; 42 gives TrueType.")]},
 {"type": "Variant B", "label": "references/chart-recipes.md blocks as a 6-panel figure (scatter, line, bar, boxplot, hist, imshow, axis formatting)", "status": "COMPLETED", "note": "All recipes build and render correctly; tick_labels= confirmed, labels= rejected.", "basic": 34, "specialized": 47,
  "assertions": [A("All chart recipes execute without warnings on 3.11.2", "PASS", "Opened recipes_pdf.png: six legible panels."),
   A("boxplot(labels=) is rejected on 3.11 while tick_labels= works", "PASS", "TypeError for labels=."),
   A("Symmetric RdBu_r imshow with 99th-percentile vmax is centred on zero", "PASS", "Colorbar -2..2 centred, white at 0."),
   A("Log y histogram and date axis recipes render", "PASS", "Opened figure; dates.png written.")]},
 {"type": "Stress", "label": "failure-modes.md claims: tight_layout vs constrained, FacetGrid, rasterization, large-N PDF size", "status": "COMPLETED", "note": "tight_layout/FacetGrid/Type 3/rasterize claims verified; fig.set_rasterization_zorder does not exist and the 50 MB claim is exaggerated (MPL-003).", "basic": 31, "specialized": 42,
  "assertions": [A("tight_layout with colorbar and shared axes overlaps while constrained does not", "PASS", "Axes/colorbar overlaps 2 versus 0."),
   A("FacetGrid.set_xlabel raises AttributeError and set_axis_labels works", "PASS", "AttributeError reproduced."),
   A("fig.set_rasterization_zorder(0) exists", "FAIL", "Figure has no such method; it is an Axes method."),
   A("A vector scatter of N=100,000 yields a ~50 MB PDF", "FAIL", "18,238 real points: 272,530 B vector versus 38,984 B rasterised; extrapolates to ~1.5 MB.")]}],
"key_strengths": ["Every shipped and documented recipe executed cleanly on matplotlib 3.11.2 with TrueType embedding verified by pdffonts.", "Version drift (boxplot tick_labels, constrained layout) is already handled and checked.", "tight_layout, FacetGrid, Type 3 and rasterization failure modes are real and reproduced."],
"recommendations": [
 {"priority": "P1", "title": "MPL-001 Shipped rcParams do not yield the documented 89/180 mm journal widths", "observed_in": [1, 3], "problem": "savefig.bbox='tight' re-crops the canvas: matplotlib_phd.py writes 92.0, 91.8 and 182.7 mm pages for 89, 89 and 180 mm figures (default pad 0.1 in is not set); the SKILL.md Standard Setup gives 89.4 mm.", "root_cause": "bbox_inches='tight' overrides figsize; the script omits savefig.pad_inches.", "fix": "Drop savefig.bbox='tight' (constrained layout already prevents clipping) from both the Standard Setup and script, or document the size change and assert page width."},
 {"priority": "P1", "title": "MPL-002 List palettes bind colours to data order, not to Up/Down/NS", "observed_in": [2], "problem": "palette=['#999999','#0072B2','#D55E00'] with hue='significance' draws Up blue and Down orange on real airway data and 'ns' orange in the shipped example; the colour-to-class mapping depends on row order and the same list in seaborn.objects.", "root_cause": "seaborn maps a list palette to hue levels in order of appearance.", "fix": "Use palette={'NS':..., 'Down':..., 'Up':...} with hue_order in SKILL.md, matplotlib_phd.py and seaborn.objects scale."},
 {"priority": "P2", "title": "MPL-003 failure-modes.md contains a nonexistent method and an exaggerated claim", "observed_in": [5], "problem": "`fig.set_rasterization_zorder(0)` raises AttributeError (it is `ax.set_rasterization_zorder`); '100000 points = 50 MB PDF, 30 s open' is not reproduced (19k points = 0.27 MB); 'default rasterization can include axes' is not demonstrated.", "root_cause": "Claims written from memory.", "fix": "Use ax.set_rasterization_zorder(0), restate the size effect with a measured ratio, drop the vague mechanism."},
 {"priority": "P2", "title": "MPL-004 'SVG for editable vector' leaves text as paths", "observed_in": [3], "problem": "svg.fonttype defaults to 'path': the saved SVG has 0 <text> elements and 55 glyph uses, so text is not editable.", "root_cause": "Saving block does not set svg.fonttype.", "fix": "Set svg.fonttype='none' (with a note that fonts must be installed) or reword the claim."},
 {"priority": "P2", "title": "MPL-005 Example styling departs from the Skill's own rules", "observed_in": [1], "problem": "The cluster scatter uses cmap='tab10' (not CVD-safe) against the Okabe-Ito requirement; axes.titlesize=8 exceeds the stated 5-7 pt body-text limit; the grid titles repeat the panel tags a-f.", "root_cause": "Example written before the CVD and size rules.", "fix": "Colour clusters with the Okabe-Ito list, use titlesize 7, and drop the redundant panel titles."},
 {"priority": "P2", "title": "MPL-006 OO-API Skill mixes pyplot state calls", "observed_in": [4], "problem": "SKILL.md Color section uses plt.imshow/plt.colorbar and the recipes use plt.colorbar(..., ax=ax) while the guardrail forbids pyplot state calls after plt.subplots(n, m).", "root_cause": "Snippets not rewritten to the OO form.", "fix": "Use ax.imshow and fig.colorbar(im, ax=ax) in SKILL.md, usage-guide and chart-recipes."}]
}
json.dump(spec, open(sys.argv[1], 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
