# Builds ../eval_viewer_bio-isoform-switching.md from the report JSON plus excerpts of the logs in this folder.
import io, json, os, re
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
R = json.load(io.open(os.path.join(ROOT, "eval_report_bio-isoform-switching_result.json"), encoding="utf-8"))

def excerpt(log, pats, maxn=14, width=230):
    p = os.path.join(HERE, log)
    if not os.path.exists(p): return "(log missing)"
    out = []
    for line in io.open(p, encoding="utf-8", errors="replace"):
        line = line.rstrip()
        if any(re.search(x, line) for x in pats): out.append(line[:width])
        if len(out) >= maxn: break
    return "\n".join(out)

L = []
w = L.append
f = R["final"]; m = R["meta"]; d = R["dynamic_score"]
w("# Eval Viewer - bio-isoform-switching (second re-audit, round 2)")
w("Generated: 2026-09-20 | Source: `%s` | Category: Data Analysis | Mode: D | Complexity: Complex (N=%d)\n" % (m["source"], m["n_inputs"]))
w("Previous: original audit 66 (Beta Only) -> first re-audit 82 (Limited Release, one open P1) -> **this re-audit %d (%s %s)**, deployable=%s, veto=%s, open P0 0, open P1 0, 5 open P2.\n" % (f["score"], f["grade_symbol"], f["grade"], f["deployable"], f["veto_override"]))
w("Data: SYNTHETIC planted-truth sets generated by the auditors (`run/data`, deleted after the run; regenerate with `run/99_run_order.sh`) and real nf-core rnasplice chrX (2 GBR v 2 YRI, Salmon 2.7.0, GRCh37) from `audit-envs\\alternative-splicing\\public-data`. Skill copied to `run/skill/` (byte-identical to commit 48e3cbc, sha256 checked); nothing written in the worktree.\n")
w("## Summary table\n")
w("| Input | Type | Basic /40 | Specialized /60 | Total /100 | Assertions | Status | Executed |")
w("|---|---|---|---|---|---|---|---|")
for i in d["inputs"]:
    w("| %d%s | %s | %d | %d | %d | %d/%d PASS | %s | %s |" % (i["index"], " (NEW)" if i["new_input"] else "", i["type"], i["basic"], i["specialized"], i["total"], i["assertions_passed"], i["assertions_total"], i["status_flag"], "yes" if i["executed"] else "no"))
w("\n**Execution average: %.1f / 100** | **Assertion pass rate: %d/%d** | Static %d/100 | Final = %.1f + %.1f = **%d (%s)**" % (d["execution_avg"], d["assertion_pass_rate"]["passed"], d["assertion_pass_rate"]["total"], R["static_score"]["subtotal"], f["static_weighted"], f["dynamic_weighted"], f["score"], f["grade"]))
w("Floors for Limited Release met: static >= 70, execution >= 75, Layer 1 avg %.1f >= 28, Layer 2 avg %.1f >= 42, assertions >= 80%%.\n" % (sum(i["basic"] for i in d["inputs"]) / len(d["inputs"]), sum(i["specialized"] for i in d["inputs"]) / len(d["inputs"])))
w("Executed 10/10 inputs. Not executed inside them: SignalP, IUPred2A, NetSurfP, DeepTMHMM (licence / cloud), tximeta `rowData(se)$gene_id` on real output, IsoformSwitchAnalyzeR 2.8-2.12 (source read only).\n")
w("## Vetoes\n")
sv = R["veto_gates"]["skill_veto"]; rv = R["veto_gates"]["research_veto"]
w("Skill veto: T1 %s, T2 %s, T3 %s, T4 %s. Research veto: M1 %s, M2 %s, M3 %s, M4 %s. No veto fired.\n" % (sv["stability"], sv["contract"], sv["determinism"], sv["security"], rv["scientific_integrity"]["result"], rv["practice_boundaries"]["result"], rv["methodological_ground"]["result"], rv["code_usability"]["result"]))
w("T3 note: the only run-to-run variation found is importRdata's sva step on a 2 v 2 design (one seed of six flips 11 -> 0 genes); 3 v 3 and larger, and the true chrX split, were stable across six seeds. Recorded as P2, not a veto.\n")
w("## Static score (25 criteria, 8 categories)\n")
w("| Category | Score | Note |"); w("|---|---|---|")
for k, c in R["static_score"]["categories"].items(): w("| %s | %d/%d | %s |" % (k, c["score"], c["max"], c["note"]))
w("| **Subtotal** | **%d/100** | |\n" % R["static_score"]["subtotal"])
w("## Round-2 targets, one line each (evidence in the inputs below)\n")
w("| Target | Verdict |"); w("|---|---|")
for a, b in [
    ("Null check: reproduce 11/15 vs 20 raw, 0 default", "Reproduced exactly with the Skill's own blocks (`run/71`, `run/96`): raw 20/11/15, default 0/0/0; manual 13/0/4, DRIMSeq 11/4/3, both 7/0/1, ISAR calls confirmed 12/0/4."),
    ("Permutation block as written", "Runs verbatim on chrX (observed 20, permuted 15 and 11), 3v3, 6v6 and an unbalanced 3v5 (valid distinct size-preserving splits). Cost is about 30 s per call x (splits + 1), so 4-5 minutes at 9-10 splits."),
    ("Guidance honest and sufficient?", "Honest: yes. Sufficient: yes with the check. On my pure-null heterogeneity sets false calls per 250 genes were 4-5 at n=2, 1-4 at n=3, 0-2 at n=4, 0 at n=6, and the block separated planted (22, 20) from permuted (max 6, 0). n=3 is not clean, which the Skill's 'check first' advice covers. One gap: sva makes n=2 lists seed-dependent (P2)."),
    ("Sample-ID error message", "Fixed: names the IDs in five cases (`run/93c`)."),
    ("Citation Han et al. 2026", "Verified: NAR Genom Bioinform 8(3):lqag098, DOI 10.1093/nargab/lqag098 (web search, PMC13504270; bioRxiv 10.64898/2025.12.08.693027 in the results). The page text was read through a summarising tool, so its wording is paraphrased."),
    ("Corrected specificity / length ranges / dmFilter message", "All three reproduce: 0.64/0.95 after analyzeORF; 0.019-575.8 (EffectiveLength) and 0.023-18.1 (Length); message with its `min_samps_gene_expr >= 0 &&` clause."),
    ("Shipped example from a clean copy", "Demo: 35 isoforms / 14 genes, 14/14 planted, 8/8 NMD, DEMO OK (three separate sessions). Real chrX: 26 isoforms / 20 genes, PDF, n<3 warning. Also 4v7 + batch and odd-ID 3v5: 20/20 planted."),
    ("Core detection must not regress", "20/20 planted on 3v3, 4v7, 5v5, 6v6, 3v5 (through block and example)."),
    ("SKILL.md length", "550 lines / 43.7 KB (~11k tokens): still usable, every fenced block runs, but static performance score 4/8 and a references/ split is now clearly due (P2)."),
    ("Does ISAR v2 select the DTU test automatically?", "Partly. `isoformSwitchAnalysisPart1()` does (any condition > 5 replicates -> satuRn, else DEXSeq), in installed 2.6.0 (traced run, `run/99b`) and in the 2.10.0 / 2.12.0 sources (`run/98`). `isoformSwitchTestDEXSeq()` / `isoformSwitchTestSatuRn()` only warn. The Skill's 'does not choose the test for you' and 'no newer release was available' are therefore inaccurate (P2)."),
    ("Licence-gated annotators", "Labelled 'not run' / 'read from source'; the labelling is honest. Note that 2.12.0 exports `analyzeNetSurfP3` (not `analyzeNetSurfP2`), so the NetSurfP-2 rows do not apply to the current Bioconductor release."),
    ("Defects introduced by round 2", "None in the Null check or ID message. Found alongside: manual block fails on non-syntactic IDs (pre-existing), sva seed dependence (pre-existing but now visible through the Null check table)."),
]: w("| %s | %s |" % (a, b))
w("")
w("## Detailed inputs\n")
logs = {
 1: [("10_input1.log", [r"^\[(PASS|FAIL)\]", r"planted recovered"]), ("93c_id_error_message.log", [r"^\(", r"^\[(PASS|FAIL)\]"])],
 2: [("20_input2.log", [r"^\[(PASS|FAIL)\]", r"manual DEXSeq", r"DRIMSeq:", r"gene q<0.05"])],
 3: [("30_input3.log", [r"^\[(PASS|FAIL)\]", r"Skill block:", r"^ISAR|^tximport"]), ("96_null_table.log", [r"ISAR raw", r"^\[(PASS|FAIL)\]", r"SKILL BLOCK"]), ("71.log", [r"^true|^mixed|raw-route"]), ("99c_sva_seed_determinism.log", [r"seed"]), ("99d_sva_seed_3v3.log", [r"seed"]), ("35c_mixed.log", [r"Added 1 batch", r"Significant"])],
 4: [("40c.log", [r"^\[(PASS|FAIL)\]", r"consequence rows", r"NMD:"]), ("41.log", [r"sens", r"orf_origin"]), ("40b_external.log", [r"rc=", r"wrote"])],
 5: [("50_input5.log", [r"^\[(PASS|FAIL)\]", r"^->", r"planted 20/20"]), ("65_common_errors_rest.log", [r"^\[(PASS|FAIL)\]", r"->"])],
 6: [("60_input6.log", [r"^\[(PASS|FAIL)\]", r"swish", r"top:"]), ("61_tximeta_warning.log", [r"couldn|rowData|sha256"])],
 7: [("70_input7.log", [r"planted \d+/20", r"manual pipeline", r"wrapper"]), ("72_efflen_factor.log", [r"factor range"]), ("98_isar_newer_source.log", [r"^===|export\('analyze(NetSurf|Signal)|export\('isoformSwitchTest|high_level_functions"]), ("99b_isar_part1_autoselect.log", [r"TRACE|replicates per|Part1 lines"]), ("97_install_isar212.log", [r"ERROR|non-zero"])],
 8: [("80_input8.log", [r"^\[(PASS|FAIL)\]", r"null split"]), ("82_eval_example_new.log", [r"^\[(PASS|FAIL)\]", r"example output"])],
 9: [("91_input9.log", [r"^n=", r"workflow:", r"SKILL BLOCK", r"permutation block", r"^\[(PASS|FAIL)\]"]), ("92b_perm_block_unbalanced.log", [r"observed", r"overlap", r"^\[(PASS|FAIL)\]"])],
 10: [("92_input10.log", [r"^10|^\[(PASS|FAIL)\]|ERROR|sample dirs"]), ("94_odd_id_probe.log", [r"cols|colnames|valid"]), ("95_odd_id_workaround.log", [r"renamed|manual pipeline|^\[(PASS|FAIL)\]|stageR"]), ("93b_eval_example_odd.log", [r"^\[(PASS|FAIL)\]", r"example output"])],
}
prompts = {
 1: "Run the isoform-switch workflow from the Skill on my Salmon quants (sample dirs SRR-style, metadata table attached); 3 v 3 and 6 v 6; then compare two control halves.",
 2: "Do the DTU analysis with DRIMSeq filter, DEXSeq and stageR two-stage FDR on the same data.",
 3: "I have 2 GBR and 2 YRI chrX RNA-seq samples quantified with Salmon; find isoform switches, then tell me how far I can trust a 2 v 2 result (run the Skill's null check).",
 4: "Annotate the switches: NMD, ORF, domains (Pfam via hmmscan), coding potential (CPC2), with whatever annotators I can run.",
 5: "Same workflow, but my metadata has a batch column / is missing a sample / has version-suffixed IDs / has a single replicate.",
 6: "Use swish on Salmon Gibbs samples for DTE; import the same data via tximeta; treat a long-read count matrix.",
 7: "Is what this Skill says about IsoformSwitchAnalyzeR v2 (auto-selection, newest release, paper) and about the count route true?",
 8: "Unbalanced 4 v 7 design with a batch effect: run the block and the shipped example on my folder.",
 9: "My cohort has 2, 3, 4 or 6 subjects per group and subjects differ in isoform usage; how many false switches should I expect, and does the Skill's permutation check catch them?",
 10: "My Salmon directories are named 1-ctrl, 2-ctrl, trt.1-b ... (3 v 5): run the workflow, the manual DTU pipeline and the shipped example.",
}
for i in d["inputs"]:
    k = i["index"]
    w("### Input %d - %s%s: %s" % (k, i["type"], " (NEW)" if i["new_input"] else "", i["label"]))
    w("**Prompt (as a user would send it):** %s\n" % prompts[k])
    w("**Executed:** %s. %s\n" % ("true" if i["executed"] else "false", i["execution_note"]))
    w("**Output summary:** %s\n" % i["note"])
    w("**Key printed output (trimmed logs):**\n")
    for lg, pats in logs[k]:
        w("`run/%s`\n```\n%s\n```" % (lg, excerpt(lg, pats)))
    w("\n**Scores:** Basic %d/40 | Specialized %d/60 | Total %d/100\n" % (i["basic"], i["specialized"], i["total"]))
    w("**Assertions (%d/%d):**" % (i["assertions_passed"], i["assertions_total"]))
    for a in i["assertions"]: w("- [%s] %s - %s" % (a["result"], a["text"], a["note"]))
    w("")
w("## Code that was run\n")
w("Every script is in `run/` (logs beside them, order in `run/99_run_order.sh`). The Skill's own R blocks were extracted from `SKILL.md` by `run/03_extract_blocks.py` into `run/blocks/` and executed verbatim: `r_01` workflow, `r_02` permutation check, `r_03` consequences, `r_04` manual DTU, `r_05` confirm snippet, `r_06` swish. Generators: `02_gen_synth.R`, `04_gen_new.R`, `05_gen_het.R` (new). New this round: `91_input9_het_null.R`, `92_input10_odd_ids_unbalanced.R`, `92b`, `93*`, `94`, `95`, `96_null_table_real_chrX.R`, `97-99d` (ISAR versions, Part1 auto-selection, seed sensitivity).\n")
w("## Recommendations\n")
for r in R["recommendations"]:
    w("**[%s] %s** (inputs %s)\n- Problem: %s\n- Root cause: %s\n- Fix: %s\n" % (r["priority"], r["title"], r["observed_in"], r["problem"], r["root_cause"], r["fix"]))
w("## Key strengths\n")
for s in R["key_strengths"]: w("- " + s)
w("")
w("> Reviewer: rows below 85 are inputs 3 (seed sensitivity at n=2), 4 (licence-gated annotators unrun), 6, 7 (stale version claims) and 10 (manual block on odd IDs). None is a blocker.")
io.open(os.path.join(ROOT, "eval_viewer_bio-isoform-switching.md"), "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
print("viewer written", len(L), "lines")
