#!/usr/bin/env node
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const repositoryRoot = path.resolve(import.meta.dirname, "..");
const PRIORITIES = ["P0", "P1", "P2"];
const GENERATED =
  "Generated by `npm run audits:index` from `audits/skills/*/*/record.json` and `report.json`. Do not edit by hand.";

async function directories(directory) {
  try {
    return (await readdir(directory, { withFileTypes: true }))
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
  } catch (error) {
    if (error.code === "ENOENT") return [];
    throw error;
  }
}

async function readJson(file) {
  return JSON.parse(await readFile(file, "utf8"));
}

export async function loadAudits(auditsDirectory) {
  const skills = [];
  for (const skillId of await directories(
    path.join(auditsDirectory, "skills"),
  )) {
    const versions = [];
    for (const version of await directories(
      path.join(auditsDirectory, "skills", skillId),
    )) {
      const base = path.join(auditsDirectory, "skills", skillId, version);
      const record = await readJson(path.join(base, "record.json"));
      const report = await readJson(path.join(base, "report.json"));
      if (record.skill_id !== skillId || record.version !== version) {
        throw new Error(
          `audits/skills/${skillId}/${version}: record.json names ${record.skill_id}/${record.version}`,
        );
      }
      for (const recommendation of report.recommendations ?? []) {
        if (!PRIORITIES.includes(recommendation.priority)) {
          throw new Error(
            `audits/skills/${skillId}/${version}: unknown priority ${recommendation.priority}`,
          );
        }
      }
      versions.push({ skillId, version, record, report });
    }
    const names = new Set(versions.map((entry) => entry.version));
    for (const entry of versions) {
      const { supersedes } = entry.record;
      if (supersedes && !names.has(supersedes)) {
        throw new Error(
          `audits/skills/${skillId}/${entry.version}: supersedes missing version ${supersedes}`,
        );
      }
      entry.supersededBy =
        versions.find((other) => other.record.supersedes === entry.version)
          ?.version ?? null;
    }
    const latest = versions.filter((entry) => !entry.supersededBy);
    if (latest.length !== 1) {
      throw new Error(
        `audits/skills/${skillId}: expected one latest version, found ${latest.length}`,
      );
    }
    skills.push({
      skillId,
      latest: latest[0],
      earlier: versions.filter((entry) => entry.supersededBy),
    });
  }

  return { skills };
}

const cell = (text) =>
  String(text ?? "")
    .replace(/\s+/g, " ")
    .replace(/\|/g, "\\|")
    .trim();

// Auditors write observed_in as either a list of inputs or a single prose string.
const observedIn = ({ observed_in: observed }) =>
  cell(Array.isArray(observed) ? observed.join(", ") : observed) || "—";

const sourceLink = ({ source }) =>
  `[${source.repository}@${source.commit.slice(0, 7)}](${source.url})`;

const recordLink = (entry, label = "viewer") =>
  `[${label}](skills/${entry.skillId}/${encodeURI(entry.version)}/viewer.md)`;

const openCounts = (report) =>
  PRIORITIES.map(
    (priority) =>
      (report.recommendations ?? []).filter(
        (recommendation) => recommendation.priority === priority,
      ).length,
  ).join(" / ");

const finish = (lines) => `${lines.join("\n").replace(/\n+$/, "")}\n`;

export function renderIndex({ skills }) {
  const lines = ["# Audit index", "", GENERATED, ""];

  lines.push(
    "## Skills — latest audit",
    "",
    "| Skill | Score | Grade | Deployable | Open P0 / P1 / P2 | Audited version | Skill author | Audited on | Record |",
    "| --- | ---: | --- | --- | --- | --- | --- | --- | --- |",
  );
  for (const { latest } of skills) {
    const { final } = latest.report;
    const { source, audit } = latest.record;
    lines.push(
      `| \`${latest.skillId}\` | ${final.score} | ${cell(final.grade)} | ${final.deployable ? "yes" : "no"} | ${openCounts(latest.report)} | ${sourceLink(latest.record)} | [${cell(source.author)}](${source.author_url}) | ${cell(audit.audited_on)} | ${recordLink(latest)} |`,
    );
  }
  lines.push("");

  const earlier = skills.flatMap((skill) => skill.earlier);
  lines.push("## Skills — earlier audits", "");
  if (earlier.length === 0) {
    lines.push("None.");
  } else {
    lines.push(
      "| Skill | Score | Grade | Audited version | Superseded by | Record |",
      "| --- | ---: | --- | --- | --- | --- |",
    );
    for (const entry of earlier) {
      const { final } = entry.report;
      lines.push(
        `| \`${entry.skillId}\` | ${final.score} | ${cell(final.grade)} | ${sourceLink(entry.record)} | \`${entry.supersededBy}\` | ${recordLink(entry)} |`,
      );
    }
  }
  return finish(lines);
}

export function renderBacklog({ skills }) {
  const items = skills.flatMap(({ latest }) =>
    (latest.report.recommendations ?? []).map((recommendation) => ({
      entry: latest,
      recommendation,
    })),
  );
  const lines = [
    "# Improvement backlog",
    "",
    GENERATED,
    "",
    "Open recommendations from the latest audit of each Skill, most severe first and lowest-scoring Skill first within a priority. To take one on, read the linked viewer, fix the Skill in its source repository, and ask for a re-audit (see [README.md](README.md)).",
    "",
  ];
  for (const priority of PRIORITIES) {
    const group = items
      .filter(({ recommendation }) => recommendation.priority === priority)
      .sort(
        (a, b) =>
          a.entry.report.final.score - b.entry.report.final.score ||
          a.entry.skillId.localeCompare(b.entry.skillId),
      );
    lines.push(`## ${priority} (${group.length})`, "");
    if (group.length === 0) {
      lines.push("None open.", "");
      continue;
    }
    for (const { entry, recommendation } of group) {
      const { final } = entry.report;
      lines.push(
        `### \`${entry.skillId}\` — ${cell(recommendation.title)}`,
        "",
        `- Skill: ${final.score}, ${cell(final.grade)} · ${sourceLink(entry.record)} · ${recordLink(entry)}`,
        `- Observed in inputs: ${observedIn(recommendation)}`,
        `- Problem: ${cell(recommendation.problem)}`,
        `- Root cause: ${cell(recommendation.root_cause)}`,
        `- Fix: ${cell(recommendation.fix)}`,
        "",
      );
    }
  }
  return finish(lines);
}

async function main() {
  const check = process.argv.includes("--check");
  const auditsDirectory = path.join(repositoryRoot, "audits");
  const audits = await loadAudits(auditsDirectory);
  const outputs = {
    "INDEX.md": renderIndex(audits),
    "BACKLOG.md": renderBacklog(audits),
  };
  const stale = [];
  for (const [name, text] of Object.entries(outputs)) {
    const file = path.join(auditsDirectory, name);
    if (!check) {
      await writeFile(file, text);
      continue;
    }
    let current = null;
    try {
      current = (await readFile(file, "utf8")).replace(/\r\n/g, "\n");
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    if (current !== text) stale.push(`audits/${name}`);
  }
  if (stale.length > 0) {
    console.error(
      `Stale generated audit files: ${stale.join(", ")}. Run npm run audits:index.`,
    );
    process.exit(1);
  }
  console.log(
    check
      ? "Audit index is up to date"
      : "Wrote audits/INDEX.md and audits/BACKLOG.md",
  );
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  await main();
}
