#!/usr/bin/env node
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const repositoryRoot = path.resolve(import.meta.dirname, "..");
const PRIORITIES = ["P0", "P1", "P2"];
const CORPUS_STATES = new Set([
  "ready",
  "refined",
  "remaining",
  "excluded",
  "out_of_scope",
]);
const CATEGORY_ORDER = [
  "Evidence Insight",
  "Protocol Design",
  "Data Analysis",
  "Academic Writing",
  "Other",
  "Unclassified",
];
const GENERATED =
  "Generated by `npm run audits:index` from `audits/skills/*/*/record.json` and `report.json`. Do not edit by hand.";
const STATUS_GENERATED =
  "Generated by `npm run audits:index` from `audits/CORPUS.json` and the latest published audit records. Do not edit by hand.";

export function gradeForScore(score) {
  if (score >= 85) return "Production Ready";
  if (score >= 75) return "Limited Release";
  if (score >= 60) return "Beta Only";
  return "Reject";
}

async function directories(directory) {
  try {
    return (await readdir(directory, { withFileTypes: true }))
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
  } catch (error) {
    if (error.code === "ENOENT") return [];
    throw error;
  }
}

async function readJson(file) {
  return JSON.parse(await readFile(file, "utf8"));
}

const readyProviderSkill = (skill) =>
  skill.score >= 85 &&
  skill.grade === "Production Ready" &&
  skill.deployable === true &&
  skill.open_p0 === 0 &&
  skill.fix_pass === "done" &&
  skill.reaudit === "not needed";

export async function buildCorpusFromProvider(providerDirectory) {
  const provenance = await readJson(
    path.join(providerDirectory, "PROVENANCE.json"),
  );
  const remaining = await readJson(
    path.join(providerDirectory, "REMAINING.json"),
  );
  if (!Array.isArray(provenance.skills)) {
    throw new Error("PROVENANCE.json: skills must be an array");
  }
  for (const name of ["remaining", "excluded", "out_of_scope"]) {
    if (!Array.isArray(remaining[name])) {
      throw new Error(`REMAINING.json: ${name} must be an array`);
    }
  }

  const rows = [];
  const add = (skill, state) => {
    if (!skill.id || !skill.upstream_path) {
      throw new Error(`provider ${state} entry is missing id or upstream_path`);
    }
    rows.push({
      id: skill.id,
      upstream_path: skill.upstream_path,
      category: skill.category ?? null,
      state,
    });
  };
  for (const skill of provenance.skills) {
    add(skill, readyProviderSkill(skill) ? "ready" : "refined");
  }
  for (const skill of remaining.remaining) add(skill, "remaining");
  for (const skill of remaining.excluded) add(skill, "excluded");
  for (const skill of remaining.out_of_scope) add(skill, "out_of_scope");

  rows.sort((a, b) => a.id.localeCompare(b.id));
  const duplicates = rows
    .filter((row, index) => index > 0 && row.id === rows[index - 1].id)
    .map((row) => row.id);
  if (duplicates.length > 0) {
    throw new Error(`provider inventory has duplicate IDs: ${duplicates.join(", ")}`);
  }
  const expected = remaining.reconciliation?.skills_in_source_tree;
  if (Number.isInteger(expected) && expected !== rows.length) {
    throw new Error(
      `provider inventory declares ${expected} Skills but contains ${rows.length}`,
    );
  }

  const source = Object.values(provenance.sources ?? {})[0] ?? {};
  return {
    schema_version: 1,
    generated: remaining.generated ?? provenance.generated ?? null,
    source: {
      upstream: remaining.source ?? null,
      provider_repository: source.provider_repository ?? null,
      provider_ref: source.provider_ref ?? null,
      provider_skills_tree: source.provider_skills_tree ?? null,
    },
    skills: rows,
  };
}

export async function loadCorpus(corpusFile) {
  const corpus = await readJson(corpusFile);
  if (corpus.schema_version !== 1 || !Array.isArray(corpus.skills)) {
    throw new Error(`${corpusFile}: expected corpus schema_version 1`);
  }
  const seen = new Set();
  for (const skill of corpus.skills) {
    if (!skill.id || !CORPUS_STATES.has(skill.state)) {
      throw new Error(`${corpusFile}: invalid corpus entry ${skill.id ?? "<missing>"}`);
    }
    if (seen.has(skill.id)) {
      throw new Error(`${corpusFile}: duplicate Skill ${skill.id}`);
    }
    seen.add(skill.id);
  }
  return corpus;
}

export async function loadAudits(auditsDirectory) {
  const skills = [];
  for (const skillId of await directories(
    path.join(auditsDirectory, "skills"),
  )) {
    const versions = [];
    for (const version of await directories(
      path.join(auditsDirectory, "skills", skillId),
    )) {
      const base = path.join(auditsDirectory, "skills", skillId, version);
      const record = await readJson(path.join(base, "record.json"));
      const report = await readJson(path.join(base, "report.json"));
      if (record.skill_id !== skillId || record.version !== version) {
        throw new Error(
          `audits/skills/${skillId}/${version}: record.json names ${record.skill_id}/${record.version}`,
        );
      }
      for (const recommendation of report.recommendations ?? []) {
        if (!PRIORITIES.includes(recommendation.priority)) {
          throw new Error(
            `audits/skills/${skillId}/${version}: unknown priority ${recommendation.priority}`,
          );
        }
      }
      versions.push({ skillId, version, record, report });
    }
    const names = new Set(versions.map((entry) => entry.version));
    for (const entry of versions) {
      const { supersedes } = entry.record;
      if (supersedes && !names.has(supersedes)) {
        throw new Error(
          `audits/skills/${skillId}/${entry.version}: supersedes missing version ${supersedes}`,
        );
      }
      entry.supersededBy =
        versions.find((other) => other.record.supersedes === entry.version)
          ?.version ?? null;
    }
    const latest = versions.filter((entry) => !entry.supersededBy);
    if (latest.length !== 1) {
      throw new Error(
        `audits/skills/${skillId}: expected one latest version, found ${latest.length}`,
      );
    }
    const final = latest[0].report.final;
    if (final.deployable === true) {
      const expected = gradeForScore(final.score);
      if (final.grade !== expected) {
        throw new Error(
          `audits/skills/${skillId}/${latest[0].version}: score ${final.score} requires grade ${expected}, found ${final.grade}`,
        );
      }
    }
    skills.push({
      skillId,
      latest: latest[0],
      earlier: versions.filter((entry) => entry.supersededBy),
    });
  }

  return { skills };
}

const cell = (text) =>
  String(text ?? "")
    .replace(/\s+/g, " ")
    .replace(/\|/g, "\\|")
    .trim();

// Auditors write observed_in as either a list of inputs or a single prose string.
const observedIn = ({ observed_in: observed }) =>
  cell(Array.isArray(observed) ? observed.join(", ") : observed) || "—";

const sourceLink = ({ source }) =>
  `[${source.repository}@${source.commit.slice(0, 7)}](${source.url})`;

const recordLink = (entry, label = "viewer") =>
  `[${label}](skills/${entry.skillId}/${encodeURI(entry.version)}/viewer.md)`;

const openCounts = (report) =>
  PRIORITIES.map(
    (priority) =>
      (report.recommendations ?? []).filter(
        (recommendation) => recommendation.priority === priority,
      ).length,
  ).join(" / ");

const finish = (lines) => `${lines.join("\n").replace(/\n+$/, "")}\n`;

export function renderIndex({ skills }) {
  const lines = ["# Audit index", "", GENERATED, ""];

  lines.push(
    "## Skills — latest audit",
    "",
    "| Skill | Score | Grade | Deployable | Open P0 / P1 / P2 | Audited version | Skill author | Audited on | Record |",
    "| --- | ---: | --- | --- | --- | --- | --- | --- | --- |",
  );
  for (const { latest } of skills) {
    const { final } = latest.report;
    const { source, audit } = latest.record;
    lines.push(
      `| \`${latest.skillId}\` | ${final.score} | ${cell(final.grade)} | ${final.deployable ? "yes" : "no"} | ${openCounts(latest.report)} | ${sourceLink(latest.record)} | [${cell(source.author)}](${source.author_url}) | ${cell(audit.audited_on)} | ${recordLink(latest)} |`,
    );
  }
  lines.push("");

  const earlier = skills.flatMap((skill) => skill.earlier);
  lines.push("## Skills — earlier audits", "");
  if (earlier.length === 0) {
    lines.push("None.");
  } else {
    lines.push(
      "| Skill | Score | Grade | Audited version | Superseded by | Record |",
      "| --- | ---: | --- | --- | --- | --- |",
    );
    for (const entry of earlier) {
      const { final } = entry.report;
      lines.push(
        `| \`${entry.skillId}\` | ${final.score} | ${cell(final.grade)} | ${sourceLink(entry.record)} | \`${entry.supersededBy}\` | ${recordLink(entry)} |`,
      );
    }
  }
  return finish(lines);
}

export function renderBacklog({ skills }) {
  const items = skills.flatMap(({ latest }) =>
    (latest.report.recommendations ?? []).map((recommendation) => ({
      entry: latest,
      recommendation,
    })),
  );
  const lines = [
    "# Improvement backlog",
    "",
    GENERATED,
    "",
    "Open recommendations from the latest audit of each Skill, most severe first and lowest-scoring Skill first within a priority. To take one on, read the linked viewer, fix the Skill in its source repository, and ask for a re-audit (see [README.md](README.md)).",
    "",
  ];
  for (const priority of PRIORITIES) {
    const group = items
      .filter(({ recommendation }) => recommendation.priority === priority)
      .sort(
        (a, b) =>
          a.entry.report.final.score - b.entry.report.final.score ||
          a.entry.skillId.localeCompare(b.entry.skillId),
      );
    lines.push(`## ${priority} (${group.length})`, "");
    if (group.length === 0) {
      lines.push("None open.", "");
      continue;
    }
    for (const { entry, recommendation } of group) {
      const { final } = entry.report;
      lines.push(
        `### \`${entry.skillId}\` — ${cell(recommendation.title)}`,
        "",
        `- Skill: ${final.score}, ${cell(final.grade)} · ${sourceLink(entry.record)} · ${recordLink(entry)}`,
        `- Observed in inputs: ${observedIn(recommendation)}`,
        `- Problem: ${cell(recommendation.problem)}`,
        `- Root cause: ${cell(recommendation.root_cause)}`,
        `- Fix: ${cell(recommendation.fix)}`,
        "",
      );
    }
  }
  return finish(lines);
}

export function buildStatus({ skills }, corpus) {
  const audits = new Map(skills.map(({ skillId, latest }) => [skillId, latest]));
  const rows = corpus.skills.map((skill) => {
    const audit = audits.get(skill.id) ?? null;
    const category =
      audit?.report?.meta?.category ?? skill.category ?? "Unclassified";
    return {
      ...skill,
      category,
      audit,
      audited: Boolean(audit) && skill.state !== "out_of_scope",
      untouched: !audit && skill.state !== "out_of_scope",
      ready: skill.state === "ready",
      outOfScope: skill.state === "out_of_scope",
    };
  });
  const known = new Set(rows.map((row) => row.id));
  const unknownAudits = [...audits.keys()].filter((id) => !known.has(id));
  if (unknownAudits.length > 0) {
    throw new Error(
      `published audit Skill(s) absent from audits/CORPUS.json: ${unknownAudits.join(", ")}`,
    );
  }

  const categories = new Map();
  for (const row of rows) {
    const counts = categories.get(row.category) ?? {
      category: row.category,
      known: 0,
      audited: 0,
      untouched: 0,
      ready: 0,
      outOfScope: 0,
    };
    counts.known += 1;
    counts.audited += Number(row.audited);
    counts.untouched += Number(row.untouched);
    counts.ready += Number(row.ready);
    counts.outOfScope += Number(row.outOfScope);
    categories.set(row.category, counts);
  }
  const order = (name) => {
    const knownIndex = CATEGORY_ORDER.indexOf(name);
    return knownIndex === -1 ? CATEGORY_ORDER.length : knownIndex;
  };
  const categoryRows = [...categories.values()].sort(
    (a, b) =>
      order(a.category) - order(b.category) ||
      a.category.localeCompare(b.category),
  );
  const totals = categoryRows.reduce(
    (sum, row) => {
      for (const key of [
        "known",
        "audited",
        "untouched",
        "ready",
        "outOfScope",
      ]) {
        sum[key] += row[key];
      }
      return sum;
    },
    { known: 0, audited: 0, untouched: 0, ready: 0, outOfScope: 0 },
  );
  return { corpus, rows, categories: categoryRows, totals };
}

export function renderStatus(status) {
  const { corpus, rows, categories, totals } = status;
  const eligible = totals.known - totals.outOfScope;
  const coverage = eligible === 0 ? 0 : (totals.audited / eligible) * 100;
  const auditedNotReady = rows
    .filter((row) => row.audited && !row.ready && !row.outOfScope)
    .sort((a, b) => a.id.localeCompare(b.id));
  const lines = [
    "# Refinement status",
    "",
    STATUS_GENERATED,
    "",
    `Corpus snapshot: ${cell(corpus.source?.upstream) || "unspecified"}`,
    "",
    `- Audit coverage: **${totals.audited} / ${eligible} (${coverage.toFixed(1)}%)** in-scope Skills`,
    `- Untouched: **${totals.untouched}**`,
    `- Ready on the optimized shelf: **${totals.ready}**`,
    `- Out of scope: **${totals.outOfScope}**`,
    "",
    "`Audited` includes every in-scope Skill with a published latest audit, including ready Skills. `Ready` means the provider records a score of at least 85 with a Production Ready grade, deployable exact bytes, no open P0, a completed fix pass, and no pending re-audit. Marketplace intake is a separate gate before a run may call newly completed work done.",
    "",
    "## By category",
    "",
    "| Category | Known | Audited | Untouched | Ready | Out of scope |",
    "|---|---:|---:|---:|---:|---:|",
  ];
  for (const row of categories) {
    lines.push(
      `| ${cell(row.category)} | ${row.known} | ${row.audited} | ${row.untouched} | ${row.ready} | ${row.outOfScope} |`,
    );
  }
  lines.push(
    `| **Total** | **${totals.known}** | **${totals.audited}** | **${totals.untouched}** | **${totals.ready}** | **${totals.outOfScope}** |`,
    "",
    "`Unclassified` contains Skills for which neither the current audit nor the corpus snapshot supplies an authoritative category. This generator does not guess from directory names.",
    "",
    "## Audited but not ready",
    "",
  );
  if (auditedNotReady.length === 0) {
    lines.push("None.", "");
  } else {
    lines.push(
      "| Skill | Category | Score | Grade | Open P0 / P1 / P2 | Record |",
      "|---|---|---:|---|---:|---|",
    );
    for (const row of auditedNotReady) {
      const { report } = row.audit;
      lines.push(
        `| \`${row.id}\` | ${cell(row.category)} | ${report.final.score} | ${cell(report.final.grade)} | ${openCounts(report)} | ${recordLink(row.audit)} |`,
      );
    }
    lines.push("");
  }
  lines.push(
    "See [INDEX.md](INDEX.md) for every latest audit and [BACKLOG.md](BACKLOG.md) for open findings.",
  );
  return finish(lines);
}

const optionValue = (name) => {
  const index = process.argv.indexOf(name);
  if (index === -1) return null;
  const value = process.argv[index + 1];
  if (!value || value.startsWith("--")) {
    throw new Error(`${name} requires a value`);
  }
  return value;
};

async function main() {
  const check = process.argv.includes("--check");
  const refreshInventory = process.argv.includes("--refresh-inventory");
  if (check && refreshInventory) {
    throw new Error("--check and --refresh-inventory cannot be combined");
  }
  const auditsDirectory = path.join(repositoryRoot, "audits");
  const audits = await loadAudits(auditsDirectory);
  const corpusFile = path.join(auditsDirectory, "CORPUS.json");
  let corpus;
  if (refreshInventory) {
    const providerDirectory = path.resolve(
      optionValue("--provider") ??
        process.env.OASS_OPTIMIZED_CLONE ??
        path.join(repositoryRoot, "..", "optimized-scientific-skills"),
    );
    corpus = await buildCorpusFromProvider(providerDirectory);
    await writeFile(corpusFile, `${JSON.stringify(corpus, null, 2)}\n`);
  } else {
    corpus = await loadCorpus(corpusFile);
  }
  const status = buildStatus(audits, corpus);
  const outputs = {
    "INDEX.md": renderIndex(audits),
    "BACKLOG.md": renderBacklog(audits),
    "STATUS.md": renderStatus(status),
  };
  const stale = [];
  for (const [name, text] of Object.entries(outputs)) {
    const file = path.join(auditsDirectory, name);
    if (!check) {
      await writeFile(file, text);
      continue;
    }
    let current = null;
    try {
      current = (await readFile(file, "utf8")).replace(/\r\n/g, "\n");
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    if (current !== text) stale.push(`audits/${name}`);
  }
  if (stale.length > 0) {
    console.error(
      `Stale generated audit files: ${stale.join(", ")}. Run npm run audits:index.`,
    );
    process.exit(1);
  }
  console.log(
    check
      ? "Generated audit views are up to date"
      : `Wrote audits/INDEX.md, audits/BACKLOG.md, and audits/STATUS.md${refreshInventory ? "; refreshed audits/CORPUS.json" : ""}`,
  );
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  await main();
}
