# Independent regression checks of first-loop corrections GG-001/002/003/005/007/008 on the exact candidate.
a <- commandArgs(TRUE); skill <- a[1]; out <- a[2]; dir.create(out, FALSE, TRUE); setwd(out)
suppressMessages({library(ggplot2); library(ggrepel); library(patchwork)})
cat("ggplot2", as.character(packageVersion("ggplot2")), "\n")
chk <- function(l, c) cat(sprintf("[%s] %s\n", if (isTRUE(c)) "PASS" else "FAIL", l)); flush(stdout())
suppressMessages(source(file.path(skill, "scripts/publication_figures.R")))
raw <- read.csv("F:/OpenScience/audit-envs/data-visualization/public-data/differential-expression/airway_dex_deseq2_results.csv")
W <- character(0); hw <- function(w) { W <<- c(W, conditionMessage(w)); invokeRestart("muffleWarning") }
p <- withCallingHandlers(create_volcano(raw), warning = hw); b <- withCallingHandlers(ggplot_build(p), warning = hw)
cat("create_volcano build warnings:", if (length(W)) paste(unique(W), collapse = " | ") else "none", "\n")
r <- raw[!is.na(raw$padj), ]; d <- p$data
# GG-001 independent
chk("GG-001 plotted y == -log10(padj) recomputed from CSV", isTRUE(all.equal(b$data[[1]]$y, -log10(r$padj))))
cls <- ifelse(r$padj < .05 & r$log2FoldChange > 1, "Up", ifelse(r$padj < .05 & r$log2FoldChange < -1, "Down", "NS"))
cat("classes Up/Down/NS (independent):", paste(table(factor(cls, c("Up","Down","NS"))), collapse = "/"), "| helper:", paste(table(factor(d$significance, c("Up","Down","NS"))), collapse = "/"), "\n")
chk("GG-001 classes equal independent", identical(as.character(d$significance), cls))
lay <- sapply(b$data, function(x) if ("yintercept" %in% names(x)) x$yintercept[1] else NA)
hy <- lay[!is.na(lay)][1]; chk(sprintf("GG-001 hline layer y = %.4f = -log10(0.05)", hy), isTRUE(all.equal(hy, -log10(0.05))))
colored <- -log10(r$padj[cls != "NS"]); chk("GG-001 smallest coloured -log10(padj) >= line; largest grey |LFC|>1 point <= line", min(colored) >= hy && max(-log10(r$padj[cls == "NS" & abs(r$log2FoldChange) > 1])) <= hy)
yl <- paste(deparse(p$labels$y), collapse = "")
chk("GG-001 y axis title is -log10 adjusted P", grepl("log", yl) && grepl("adjusted", yl))
p01 <- create_volcano(raw, fdr_threshold = 0.01); lay01 <- sapply(ggplot_build(p01)$data, function(x) if ("yintercept" %in% names(x)) x$yintercept[1] else NA)
chk("fdr_threshold=0.01 moves hline to 2", isTRUE(all.equal(lay01[!is.na(lay01)][1], 2)))
lab <- d$label[d$label != ""]; chk("default Ensembl labels = 3 smallest padj", setequal(lab, raw$gene[order(raw$padj)][1:3]))
p5 <- create_volcano(raw, top_n = 5); chk("top_n = 5 override draws 5 labels", sum(p5$data$label != "") == 5)
# GG-002
save_publication_figure(p, "pub_default"); save_publication_figure(p, "pub_183", width = 183, height = 120)
cat("png px default:", paste(dim(png::readPNG("pub_default.png"))[2:1], collapse = "x"), "(expect ~1051x827) ; 183x120:", paste(dim(png::readPNG("pub_183.png"))[2:1], collapse = "x"), "(expect 2161x1417)\n")
# GG-003
tp <- theme_publication()
chk("GG-003 theme_publication: blank panel grid", inherits(tp$panel.grid, c("ggplot2::element_blank", "element_blank")))
chk("GG-003 okabe_ito has 8 colours, first two #0072B2/#D55E00", length(okabe_ito) == 8 && identical(okabe_ito[1:2], c('#0072B2', '#D55E00')))
set.seed(7); df <- data.frame(g = rep(c("A","B","C"), each = 20), v = c(rnorm(20), rnorm(20, 1), rnorm(20, 2)))
pc <- prcomp(mtcars[, -1], scale. = TRUE); ve <- 100 * pc$sdev^2 / sum(pc$sdev^2)
pdf_ <- data.frame(pc$x[, 1:2], cyl = factor(mtcars$cyl), am = factor(mtcars$am), var_explained = ve[1:2])
bp <- create_boxplot(df, "g", "v", "g"); pp <- create_pca_plot(pdf_, "cyl", "am")
m <- create_multi_panel(p, bp, pp)
fillc <- toupper(unique(ggplot_build(bp)$data[[1]]$fill)); cat("boxplot fills:", paste(fillc, collapse = " "), "\n")
chk("GG-003 boxplot fills are Okabe-Ito 1-3", all(fillc %in% toupper(okabe_ito[1:3])))
pcc <- toupper(unique(ggplot_build(pp)$data[[1]]$colour)); cat("PCA colours:", paste(pcc, collapse = " "), "\n")
chk("GG-003 PCA colours are Okabe-Ito 1-3", all(pcc %in% toupper(okabe_ito[1:3])))
chk("GG-003 multi-panel keeps theme_publication in every sub-plot", all(sapply(m$patches$plots, function(x) inherits(x$theme$panel.grid, c("ggplot2::element_blank", "element_blank")))) && inherits(m$theme$panel.grid, c("ggplot2::element_blank", "element_blank")) | length(m$patches$plots) == 2)
ggsave("multi3_183x150.png", m, width = 183, height = 150, units = "mm", dpi = 150)
# GG-008
j1 <- ggplot_build(create_boxplot(df, "g", "v", "g"))$data[[2]]$x; j2 <- ggplot_build(create_boxplot(df, "g", "v", "g"))$data[[2]]$x; chk("GG-008 boxplot jitter reproducible across calls", identical(j1, j2))
chk("GG-008 boxplot median == raw median (A,B,C)", isTRUE(all.equal(ggplot_build(bp)$data[[1]]$middle, as.numeric(tapply(df$v, df$g, median)))))
e <- tryCatch(create_pca_plot(pdf_[, c("PC1","PC2","cyl")], "cyl"), error = function(e) conditionMessage(e)); cat("no var_explained ->", e, "\n"); chk("GG-008 missing var_explained error clear", grepl("var_explained", e))
many <- cbind(pdf_, grp = factor(rep(letters[1:12], length.out = 32))); e <- tryCatch(create_pca_plot(many, "grp"), error = function(e) conditionMessage(e)); cat("12 groups ->", e, "\n"); chk("GG-008 >8 groups error clear", grepl("Okabe-Ito", e))
chk("PCA labels equal prcomp variance", pp$labels$x == sprintf("PC1 (%s%%)", round(ve[1], 1)) && pp$labels$y == sprintf("PC2 (%s%%)", round(ve[2], 1)))
chk("boxplot without fill_var builds", !inherits(try(ggplot_build(create_boxplot(df, "g", "v")), silent = TRUE), "try-error"))
e <- tryCatch(create_volcano(raw[, c("log2FoldChange", "gene")]), error = function(e) "err"); chk("missing padj column raises an error (not silent)", identical(e, "err"))
e <- tryCatch(create_volcano(raw, label_col = "nope"), error = function(e) conditionMessage(e)); cat("bad label_col ->", substr(e, 1, 90), "\n"); chk("bad label_col raises error", is.character(e))
# top_n NULL heuristic boundary
tmp <- raw; tmp$lab9 <- paste0("GENE", sprintf("%05d", seq_len(nrow(tmp)))); v9 <- create_volcano(tmp, label_col = "lab9"); chk("9-char labels -> 3 labels", sum(v9$data$label != "") == 3)
tmp$lab8 <- paste0("GENE", sprintf("%04d", seq_len(nrow(tmp)))); v8 <- create_volcano(tmp, label_col = "lab8"); chk("8-char labels -> 10 labels", sum(v8$data$label != "") == 10)
few <- raw[!is.na(raw$padj), ][1:4, ]; vf <- tryCatch(create_volcano(few), error = function(e) conditionMessage(e)); cat("4-row input ->", if (inherits(vf, "ggplot")) paste("ok,", sum(vf$data$label != ""), "labels") else vf, "\n")
fac <- raw; fac$gene <- factor(fac$gene); vfac <- tryCatch(create_volcano(fac), error = function(e) conditionMessage(e)); cat("factor label col ->", if (inherits(vfac, "ggplot")) paste("ok,", sum(vfac$data$label != ""), "labels") else vfac, "\n")
sig0 <- raw; sig0$padj <- 0.9; z <- tryCatch({suppressWarnings(ggplot_build(create_volcano(sig0))); "builds"}, error = function(e) conditionMessage(e)); cat("no significant genes ->", z, "\n")
na_lab <- raw; na_lab$gene[order(na_lab$padj)[1]] <- NA; z <- tryCatch(suppressWarnings(ggplot_build(create_volcano(na_lab))), error = function(e) conditionMessage(e)); cat("NA label among top10 ->", if (is.character(z)) z else "builds", "\n")
