#!/bin/bash
# Order in which the scripts in this folder were run (every script here was executed; logs sit beside them). R goes through the env's r.sh; WSL through wsl_run.sh.
# work/ (staged copies, .rds, sequences, real GTF/FASTA copies) and data/synthB (regenerated by 50_input5) were deleted after the run.
export PYTHONIOENCODING=utf-8
R=F:/OpenScience/audit-envs/alternative-splicing/r.sh; W=F:/OpenScience/audit-envs/alternative-splicing/wsl_run.sh
cd F:/OpenScience/audits/bio-isoform-switching/run; mkdir -p work
python 03_extract_blocks.py                     # SKILL.md fenced blocks -> blocks/ (every test executes the Skill text verbatim)
bash $R 02_gen_synth.R                          # regression synthetic set (seed 20260920) -> data/synth
bash $R 04_gen_new.R data/new1 8801 4 7 batch   # NEW set: 4 v 7, batch effect, log-uniform exon sizes
bash $R 04_gen_new.R data/new2 8802 5 5         # NEW set: 5 v 5
bash $R 10_input1_canonical.R   > 10_input1.log 2>&1
bash $R 20_input2_manual_dtu.R  > 20_input2.log 2>&1
bash $R 30_input3_real_chrX.R   > 30_input3.log 2>&1
bash 35_example_runs.sh                         # shipped example: demo, real chrX, mixed labels, bad metadata (logs 35a-35d)
bash $R skill/examples/isoform_switch_analysis.R > 35a_demo_rerun.log 2>&1
bash $R 40a_input4_prep.R       > 40a.log 2>&1
bash $W 'bash /mnt/openscience/audits/bio-isoform-switching/run/40b_external.sh' > 40b_external.log 2>&1
bash $R 40c_consequences.R      > 40c.log 2>&1
bash $R 40d_real_consequences.R > 40d.log 2>&1
bash $R 41_orf_overwrite_check.R > 41.log 2>&1
bash $R 50_input5_stress_adversarial.R > 50_input5.log 2>&1
bash $R 60_input6_swish.R       > 60_input6.log 2>&1
bash $R 61_tximeta_warning.R    > 61_tximeta_warning.log 2>&1
bash $R 62_isar_news.R          > 62_isar_news.log 2>&1
bash 63_converter_checks.sh     > 63_converter_checks.log 2>&1
bash $R 64_isar_source_dump.R   > 64_isar_source_dump.log 2>&1
bash $R 65_common_errors_rest.R > 65_common_errors_rest.log 2>&1
bash $R 70_input7_new_count_route.R > 70_input7.log 2>&1
bash $R 71_real_label_permutation.R > 71.log 2>&1
bash $R 72_efflen_factor.R      > 72_efflen_factor.log 2>&1
bash $R 80_input8_new_unbalanced.R > 80_input8.log 2>&1
bash 81_input8_example.sh
bash $R 82_eval_example_new.R   > 82_eval_example_new.log 2>&1
# Pfam-A.clans.tsv.gz was downloaded once with: curl -sS -L -o work/annot_dl/Pfam-A.clans.tsv.gz https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.clans.tsv.gz
# 90_build_report.py writes ../eval_report_bio-isoform-switching_result.json
