.libPaths(c('F:/OpenScience/audit-envs/mass-spec-proteomics-analyst/R-lib', .libPaths()))
cat('RSTUDIO_PANDOC env:', Sys.getenv('RSTUDIO_PANDOC'), '\n')
cat('rmarkdown installed:', requireNamespace('rmarkdown', quietly=TRUE), '\n')
cat('rmarkdown version:', as.character(packageVersion('rmarkdown')), '\n')
cat('pandoc_available (before):', rmarkdown::pandoc_available(), '\n')
Sys.setenv(RSTUDIO_PANDOC='F:/OpenScience/audit-envs/mass-spec-proteomics-analyst/tools/pandoc/pandoc-3.11')
cat('pandoc_available (after RSTUDIO_PANDOC):', rmarkdown::pandoc_available(), '\n')
cat('pandoc_version:', as.character(rmarkdown::pandoc_version()), '\n')
cat('PTXQC:', as.character(packageVersion('PTXQC')), '\n')
