#!/bin/bash
# Build the SYNTHETIC datasets. Runs in WSL as-core (pysam). Run via: wsl_run.sh 'bash /mnt/openscience/audits/bio-differential-splicing/run/01_make_data.sh'
export PYTHONDONTWRITEBYTECODE=1
R=/mnt/openscience/audits/bio-differential-splicing/run
mkdir -p $R/data
CORE="micromamba run -n as-core"
# regression sim (first audit's generator, same seed 20260920): 3 replicates x groups A,B,C, SE only
$CORE python $R/make_sim.py $R/data/sim $R/data/sim 2>&1 | tail -2
# NEW sims (re-auditor's own generator, own seeds)
$CORE python $R/make_sim2.py main   $R/data/sim2  $R/data/sim2  91731 2>&1 | tail -2
$CORE python $R/make_sim2.py batch  $R/data/sim2b $R/data/sim2b 91732 2>&1 | tail -2
$CORE python $R/make_sim2.py paired $R/data/sim2p $R/data/sim2p 91733 2>&1 | tail -2
# regression check: the planted exon-skipping truth file of the first audit is regenerated byte-identically
cmp $R/data/sim/truth.tsv /mnt/openscience/audits/_pre-fix-20260920/bio-differential-splicing/run/data/sim/truth.tsv && echo "sim truth.tsv identical to the first audit's"
cmp $R/data/sim/counts.tsv /mnt/openscience/audits/_pre-fix-20260920/bio-differential-splicing/run/data/sim/counts.tsv && echo "sim counts.tsv identical to the first audit's"
for d in sim2 sim2b sim2p; do echo "$d: $(ls $R/data/$d/*.bam | wc -l) bams"; done
awk -F'\t' 'NR>1{c[$3]++} END{for(k in c) print k, c[k]}' $R/data/sim2/truth.tsv
